In [2]:
import os
os.getcwd()

'C:\\Users\\Ankitha\\Big Data'

In [3]:
os.chdir("D:\\Downloads\\data\\raw")

In [4]:
import os
os.getcwd()

'D:\\Downloads\\data\\raw'

DATASET - 1

In [5]:
import pandas as pd

df = pd.read_csv("crime_dataset_india.csv")

In [40]:
df

,Report Number,Date Reported,Crime_Date,Crime_Time,Area,Crime Code,Crime_Type,Victim Age,Victim_Gender,Weapon Used,Crime Domain,Police Deployed,Case Closed,Date Case Closed,Year,Crime_Hour,Day_Night,Crime_Count
2,3,02-01-2020 05:00,2020-01-01 02:00:00,2020-01-01 14:30:00,Ludhiana,271,KIDNAPPING,48,F,Blunt Object,Other Crime,15,No,NaN,2020,14,Day,1
14,15,02-01-2020 00:00,2020-01-01 14:00:00,2020-01-01 22:28:00,Bangalore,266,SEXUAL ASSAULT,77,F,NaN,Violent Crime,19,No,NaN,2020,22,Night,1
36,37,03-01-2020 05:00,2020-01-02 12:00:00,2020-01-03 00:18:00,Lucknow,187,SEXUAL ASSAULT,33,F,Blunt Object,Violent Crime,9,Yes,02-07-2020 05:00,2020,0,Night,1
56,57,06-01-2020 01:00,2020-01-03 08:00:00,2020-01-03 20:16:00,Kanpur,188,SEXUAL ASSAULT,67,F,Firearm,Violent Crime,8,Yes,20-07-2020 01:00,2020,20,Night,1
57,58,03-01-2020 18:00,2020-01-03 09:00:00,2020-01-03 09:43:00,Ahmedabad,110,ASSAULT,70,F,NaN,Violent Crime,15,No,NaN,2020,9,Day,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40118,40119,30-07-2024 03:00,2024-07-29 14:00:00,2024-07-30 08:25:00,Bangalore,127,SEXUAL ASSAULT,22,F,NaN,Violent Crime,13,Yes,03-04-2025 03:00,2024,8,Day,1
40123,40124,01-08-2024 09:00,2024-07-29 19:00:00,2024-07-30 04:04:00,Mumbai,599,KIDNAPPING,29,F,Explosives,Other Crime,4,No,NaN,2024,4,Night,1
40125,40126,01-08-2024 02:00,2024-07-29 21:00:00,2024-07-30 05:05:00,Chennai,591,KIDNAPPING,18,F,NaN,Other Crime,9,Yes,27-08-2024 02:00,2024,5,Night,1
40140,40141,31-07-2024 02:00,2024-07-30 12:00:00,2024-07-30 12:44:00,Indore,157,ASSAULT,31,F,Knife,Violent Crime,12,No,NaN,2024,12,Day,1
40151,40152,01-08-2024 00:00,2024-07-30 23:00:00,2024-07-30 23:10:00,Mumbai,106,KIDNAPPING,42,F,NaN,Other Crime,1,Yes,25-10-2024 00:00,2024,23,Night,1

In [12]:
df.columns

Index(['Report Number', 'Date Reported', 'Crime_Date', 'Crime_Time', 'Area',
       'Crime Code', 'Crime_Type', 'Victim Age', 'Victim_Gender',
       'Weapon Used', 'Crime Domain', 'Police Deployed', 'Case Closed',
       'Date Case Closed'],
      dtype='object')

In [11]:
df.head()

,Report Number,Date Reported,Crime_Date,Crime_Time,Area,Crime Code,Crime_Type,Victim Age,Victim_Gender,Weapon Used,Crime Domain,Police Deployed,Case Closed,Date Case Closed
2,3,02-01-2020 05:00,01-01-2020 02:00,01-01-2020 14:30,Ludhiana,271,KIDNAPPING,48,F,Blunt Object,Other Crime,15,No,NaN
3,4,01-01-2020 05:00,01-01-2020 03:00,01-01-2020 14:46,Pune,170,BURGLARY,49,F,Firearm,Other Crime,1,Yes,29-04-2020 05:00
4,5,01-01-2020 21:00,01-01-2020 04:00,01-01-2020 16:51,Pune,421,VANDALISM,30,F,Other,Other Crime,18,Yes,08-01-2020 21:00
6,7,01-01-2020 16:00,01-01-2020 06:00,01-01-2020 14:08,Chennai,172,VEHICLE - STOLEN,64,F,Knife,Violent Crime,13,Yes,24-03-2020 16:00
12,13,01-01-2020 16:00,01-01-2020 12:00,01-01-2020 23:14,Visakhapatnam,498,FRAUD,36,F,Poison,Other Crime,3,Yes,29-02-2020 16:00

In [7]:
df = df.rename(columns={
    "Date of Occurrence": "Crime_Date",
    "Time of Occurrence": "Crime_Time",
    "City": "Area",
    "Crime Description": "Crime_Type",
    "Victim Gender": "Victim_Gender"
})

In [13]:
df.columns

Index(['Report Number', 'Date Reported', 'Crime_Date', 'Crime_Time', 'Area',
       'Crime Code', 'Crime_Type', 'Victim Age', 'Victim_Gender',
       'Weapon Used', 'Crime Domain', 'Police Deployed', 'Case Closed',
       'Date Case Closed'],
      dtype='object')

In [14]:
df.dtypes

Report Number        int64
Date Reported       object
Crime_Date          object
Crime_Time          object
Area                object
Crime Code           int64
Crime_Type          object
Victim Age           int64
Victim_Gender       object
Weapon Used         object
Crime Domain        object
Police Deployed      int64
Case Closed         object
Date Case Closed    object
dtype: object

In [9]:
df = df[df["Victim_Gender"].str.upper() == "F"]

In [15]:
# Only if Victim_Gender was kept earlier
print(df["Victim_Gender"].unique())

['F']

In [16]:
allowed_crimes = [
    "ASSAULT",
    "SEXUAL ASSAULT",
    "KIDNAPPING",
    "RAPE"
]

df["Crime_Type"] = df["Crime_Type"].str.upper()

df = df[df["Crime_Type"].isin(allowed_crimes)]

In [18]:
df["Crime_Type"].unique()

array(['KIDNAPPING', 'SEXUAL ASSAULT', 'ASSAULT'], dtype=object)

In [19]:
df["Crime_Date"] = pd.to_datetime(df["Crime_Date"])
df["Year"] = df["Crime_Date"].dt.year

In [20]:
print(df[["Crime_Date", "Year"]].head(10))

             Crime_Date  Year
2   2020-01-01 02:00:00  2020
14  2020-01-01 14:00:00  2020
36  2020-01-02 12:00:00  2020
56  2020-01-03 08:00:00  2020
57  2020-01-03 09:00:00  2020
76  2020-01-04 04:00:00  2020
80  2020-01-04 08:00:00  2020
93  2020-01-04 21:00:00  2020
102 2020-01-05 06:00:00  2020
121 2020-01-06 01:00:00  2020

In [21]:
print(df["Year"].dtype)

int32

In [22]:
print(df["Year"].unique())

[2020 2021 2022 2023 2024]

In [27]:
df["Crime_Time"] = pd.to_datetime(df["Crime_Time"])
df["Crime_Hour"] = df["Crime_Time"].dt.hour

In [28]:
print(df[["Crime_Time", "Crime_Hour"]].head(10))

             Crime_Time  Crime_Hour
2   2020-01-01 14:30:00          14
14  2020-01-01 22:28:00          22
36  2020-01-03 00:18:00           0
56  2020-01-03 20:16:00          20
57  2020-01-03 09:43:00           9
76  2020-01-04 14:30:00          14
80  2020-01-04 23:33:00          23
93  2020-01-05 08:12:00           8
102 2020-01-05 17:43:00          17
121 2020-01-06 22:59:00          22

In [24]:
df["Crime_Time"] = pd.to_datetime(
    df["Crime_Time"],
    errors="coerce",
    dayfirst=True
)

In [25]:
print(df[["Crime_Time"]].head(10))

             Crime_Time
2   2020-01-01 14:30:00
14  2020-01-01 22:28:00
36  2020-01-03 00:18:00
56  2020-01-03 20:16:00
57  2020-01-03 09:43:00
76  2020-01-04 14:30:00
80  2020-01-04 23:33:00
93  2020-01-05 08:12:00
102 2020-01-05 17:43:00
121 2020-01-06 22:59:00

In [26]:
print(df["Crime_Time"].isna().sum())

0

In [29]:
print(df["Crime_Hour"].min(), df["Crime_Hour"].max())

0 23

In [30]:
df["Day_Night"] = df["Crime_Hour"].apply(
    lambda x: "Night" if (x >= 20 or x <= 5) else "Day"
)

In [31]:
print(df["Day_Night"].value_counts())

Day_Night
Day      1898
Night    1303
Name: count, dtype: int64

In [33]:
print(df["Year"].value_counts().sort_index())

Year
2020    814
2021    800
2022    421
2023    680
2024    486
Name: count, dtype: int64

In [32]:
df["Crime_Count"] = 1

In [34]:
print(df["Crime_Count"].unique())

[1]

In [35]:
df_clean = df[[
    "Area",
    "Crime_Type",
    "Year",
    "Crime_Count",
    "Crime_Date",
    "Crime_Hour",
    "Day_Night"
]]

In [37]:
print(df_clean.dtypes)

Area                   object
Crime_Type             object
Year                    int32
Crime_Count             int64
Crime_Date     datetime64[ns]
Crime_Hour              int32
Day_Night              object
dtype: object

df_clean

In [49]:
import os

os.makedirs("cleaned", exist_ok=True)

In [50]:
df_clean.to_csv("cleaned/crime_dataset_india_cleaned.csv", index=False)

In [51]:
print(os.listdir("cleaned"))

['crime_dataset_india_cleaned.csv']

DATASET - 2

In [53]:
import os
os.getcwd()

'D:\\Downloads\\data\\raw'

In [62]:
import os
print(os.listdir(r"D:\Downloads\data\raw"))

['c8d3ea7e-4855-45f3-9c26-557419e93b6a.csv', 'Crime against Women (2001-2022).csv', 'crime_dataset_india.csv', 'Crime_Incidents_in_2024.csv', 'Final-censusdataset-India.csv', 'Law and Order.csv', 'NCRB_CII-2019_Table_3B.2.csv', 'RS-Session-251-AS201-Table1.csv', 'women-crimedataset-India.csv']

In [117]:


import pandas as pd

df_police = pd.read_csv(r"D:\Downloads\data\raw\Law and Order.csv")

In [118]:
df_police

         Districts  Police Stations
0         ADILABAD               24
1        BHADRADRI               31
2        HYDERABAD               87
3         JAGTIAL                19
4         JANGAON                15
5     JAYASHANKAR                22
6       JOGULAMBA                14
7       KAMAREDDY                23
8      KARIMNAGAR                20
9         KHAMMAM                29
10  KOMARAM BHEEM                19
11     MAHABUBABAD               19
12    MAHABUBNAGAR               30
13     MANCHERIAL                24
14          MEDAK                21
15         MEDCHAL               23
16   NAGARKURNOOL                22
17       NALGONDA                40
18         NIRMAL                21
19      NIZAMABAD                35
20     PEDDAPALLI                19
21        RAJANNA                13
22     RANGAREDDY                50
23     SANGAREDDY                34
24       SIDDIPET                26
25       SURYAPET                27
26      VIKARABAD                23
27     WANAPARTHY                15
28   WARANGAL (R)                15
29    WARANGAL (U)               18
30        YADADRI                21

In [119]:

df_police.columns

Index(['Districts', 'Police Stations'], dtype='object')

In [120]:
df_police.head()

   Districts  Police Stations
0   ADILABAD               24
1  BHADRADRI               31
2  HYDERABAD               87
3   JAGTIAL                19
4   JANGAON                15

In [121]:
df_police = df_police.rename(columns={
    "Districts": "District",
    "Police Stations": "Police_Stations"
})

In [122]:
df_police.head()

    District  Police_Stations
0   ADILABAD               24
1  BHADRADRI               31
2  HYDERABAD               87
3   JAGTIAL                19
4   JANGAON                15

In [123]:
print(df_police["District"].head(10))

0        ADILABAD
1       BHADRADRI
2       HYDERABAD
3        JAGTIAL
4        JANGAON
5    JAYASHANKAR
6      JOGULAMBA
7      KAMAREDDY
8     KARIMNAGAR
9        KHAMMAM
Name: District, dtype: object

In [124]:
print(df_police["District"].str.isupper().all())

True

In [125]:
df_police["District"] = df_police["District"].str.strip().str.upper()

“We standardized district names to ensure consistency across datasets.”

In [127]:
print(df_police["District"].head(10))

0       ADILABAD
1      BHADRADRI
2      HYDERABAD
3        JAGTIAL
4        JANGAON
5    JAYASHANKAR
6      JOGULAMBA
7      KAMAREDDY
8     KARIMNAGAR
9        KHAMMAM
Name: District, dtype: object

In [128]:
print(df_police["District"].str.isupper().value_counts())

District
True    31
Name: count, dtype: int64

In [129]:
df_police["District"].apply(lambda x: x != x.strip()).sum()

0

In [130]:
print(sorted(df_police["District"].unique())[:10])

['ADILABAD', 'BHADRADRI', 'HYDERABAD', 'JAGTIAL', 'JANGAON', 'JAYASHANKAR', 'JOGULAMBA', 'KAMAREDDY', 'KARIMNAGAR', 'KHAMMAM']

In [131]:
print(set(df_clean["Area"]).intersection(set(df_police["District"])))

set()

set( ) means:
There are NO common values between Area and District.

“The crime dataset is city-level while the police station dataset is district-level, so they are used independently for analytical context rather than direct joins.”

In [133]:
df_police["Police_Stations"] = df_police["Police_Stations"].astype(int)

In [134]:
df_police["Police_Stations"].dtype

dtype('int32')

In [135]:


df_police.to_csv(r"D:\Downloads\data\cleaned\police_stations_by_district_cleaned.csv", index=False)

In [137]:
print(os.listdir(r"D:\Downloads\data\cleaned"))

['crime_dataset_india_cleaned.csv', 'police_stations_by_district_cleaned.csv']

In [138]:
df_police

         District  Police_Stations
0        ADILABAD               24
1       BHADRADRI               31
2       HYDERABAD               87
3         JAGTIAL               19
4         JANGAON               15
5     JAYASHANKAR               22
6       JOGULAMBA               14
7       KAMAREDDY               23
8      KARIMNAGAR               20
9         KHAMMAM               29
10  KOMARAM BHEEM               19
11    MAHABUBABAD               19
12   MAHABUBNAGAR               30
13     MANCHERIAL               24
14          MEDAK               21
15        MEDCHAL               23
16   NAGARKURNOOL               22
17       NALGONDA               40
18         NIRMAL               21
19      NIZAMABAD               35
20     PEDDAPALLI               19
21        RAJANNA               13
22     RANGAREDDY               50
23     SANGAREDDY               34
24       SIDDIPET               26
25       SURYAPET               27
26      VIKARABAD               23
27     WANAPARTHY               15
28   WARANGAL (R)               15
29   WARANGAL (U)               18
30        YADADRI               21

In [139]:
print(df.dtypes)

District           object
Police_Stations     int32
dtype: object

We can use district-wise police station data as a supporting dataset to contextualize risk levels and policing coverage in women safety analysis.

DATASET - 3

In [141]:
import pandas as pd

df_ncrb = pd.read_csv("women-crimedataset-India.csv")

In [143]:
df_ncrb

,STATE/UT,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS,KIDNAPPING AND ABDUCTION OF OTHERS,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES
0,ANDHRA PRADESH,ADILABAD,2001.0,101,60,50,0,50,46,30,16,16,149,34,175,0
1,ANDHRA PRADESH,ANANTAPUR,2001.0,151,125,23,0,23,53,30,23,7,118,24,154,0
2,ANDHRA PRADESH,CHITTOOR,2001.0,101,57,27,0,27,59,34,25,14,112,83,186,0
3,ANDHRA PRADESH,CUDDAPAH,2001.0,80,53,20,0,20,25,20,5,17,126,38,57,0
4,ANDHRA PRADESH,EAST GODAVARI,2001.0,82,67,23,0,23,49,26,23,12,109,58,247,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11704,Lakshadweep,Lakshadweep,2020.0,0,0,3,0,0,0,0,0,0,3,1,0,0
11705,NaN,TOTAL,2020.0,0,0,3,0,0,0,0,0,0,3,1,0,0
11706,PUDUCHERRY,Puducherry,2020.0,0,0,8,0,0,0,0,0,2,25,0,9,0
11707,PUDUCHERRY,Karaikal,2020.0,0,0,0,0,0,0,0,0,0,0,0,0,0
11708,NaN,TOTAL,NaN,0,0,8,0,0,0,0,0,2,25,0,9,0

In [144]:
df_ncrb.shape

(11709, 16)

In [145]:
df_ncrb.columns

Index(['STATE/UT', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO MURDER', 'RAPE',
       'CUSTODIAL RAPE', 'OTHER RAPE', 'KIDNAPPING & ABDUCTION',
       'KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS',
       'KIDNAPPING AND ABDUCTION OF OTHERS', 'DOWRY DEATHS',
       'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'INSULT TO MODESTY OF WOMEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES'],
      dtype='object')

In [146]:
df_ncrb = df_ncrb.rename(columns={
    "STATE/UT": "State",
    "DISTRICT": "District",
    "YEAR": "Year"
})

In [147]:
print(df_ncrb.columns[:5])

Index(['State', 'District', 'Year', 'MURDER', 'ATTEMPT TO MURDER'], dtype='object')

In [148]:
crime_columns = {
    "RAPE": "RAPE",
    "CUSTODIAL RAPE": "RAPE",
    "OTHER RAPE": "RAPE",
    "KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS": "KIDNAPPING",
    "ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY": "ASSAULT"
}

df_ncrb_filtered = df_ncrb[
    ["State", "District", "Year"] + list(crime_columns.keys())
]

In [149]:
df_ncrb_filtered.head()

,State,District,Year,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY
0,ANDHRA PRADESH,ADILABAD,2001.0,50,0,50,30,149
1,ANDHRA PRADESH,ANANTAPUR,2001.0,23,0,23,30,118
2,ANDHRA PRADESH,CHITTOOR,2001.0,27,0,27,34,112
3,ANDHRA PRADESH,CUDDAPAH,2001.0,20,0,20,20,126
4,ANDHRA PRADESH,EAST GODAVARI,2001.0,23,0,23,26,109

In [150]:
df_ncrb_filtered.shape

(11709, 8)

In [151]:
df_long = df_ncrb_filtered.melt(
    id_vars=["State", "District", "Year"],
    var_name="Crime_Type",
    value_name="Crime_Count"
)

In [153]:
print(df_long.head())

            State       District    Year Crime_Type Crime_Count
0  ANDHRA PRADESH       ADILABAD  2001.0       RAPE          50
1  ANDHRA PRADESH      ANANTAPUR  2001.0       RAPE          23
2  ANDHRA PRADESH       CHITTOOR  2001.0       RAPE          27
3  ANDHRA PRADESH       CUDDAPAH  2001.0       RAPE          20
4  ANDHRA PRADESH  EAST GODAVARI  2001.0       RAPE          23

In [154]:
print(df_long.shape)

(58545, 5)

In [155]:
df_long["Crime_Type"] = df_long["Crime_Type"].map(crime_columns)

In [156]:
print(df_long["Crime_Type"].unique())

['RAPE' 'KIDNAPPING' 'ASSAULT']

In [176]:
print(df_long["Crime_Count"].dtype)

int32

In [177]:
df_long["Crime_Count"] = pd.to_numeric(
    df_long["Crime_Count"],
    errors="coerce"
)

In [178]:
print(df_long["Crime_Count"].dtype )

int32

In [179]:
print(df_long["Crime_Count"].isna().sum())

0

In [180]:
df_long = df_long[df_long["Crime_Count"] > 0]

In [181]:
print((df_long["Crime_Count"] <= 0).sum())
print(df_long.shape)

0
(40911, 5)

In [182]:
print(df_long["Crime_Count"].head(10))

0     50
1     23
2     27
3     20
4     23
6     54
7     37
8     56
9     47
10    37
Name: Crime_Count, dtype: int32

In [183]:
df_long["State"] = df_long["State"].str.upper()
df_long["District"] = df_long["District"].str.upper()
df_long["Crime_Type"] = df_long["Crime_Type"].str.upper()

In [184]:

print(df_long["State"].str.isupper().all())
print(df_long["District"].str.isupper().all())
print(df_long["Crime_Type"].str.isupper().all())

True
True
True

In [185]:
print(df_long.dtypes)

State           object
District        object
Year           float64
Crime_Type      object
Crime_Count      int32
dtype: object

In [186]:
print(df_long["Year"].dtype)

float64

In [190]:
df_long = df_long.dropna(subset=["Year"])

In [191]:
print(df_long["Year"].isna().sum())

0

In [193]:
df_long = df_long[df_long["Year"] > 0]

In [195]:
print((df_long["Year"] <= 0).sum())

0

In [196]:
df_long["Year"] = df_long["Year"].astype(int)

In [197]:
print(df_long["Year"].dtype)

int32

In [198]:
print(df_long.dtypes)

State          object
District       object
Year            int32
Crime_Type     object
Crime_Count     int32
dtype: object

In [199]:
print(df_long["Year"].min(), df_long["Year"].max())

2001 2020

In [200]:
print(df_long["District"].value_counts().head(10))

District
TOTAL                1716
SOUTH                 169
WEST                  157
NORTH                 133
HAMIRPUR              115
BILASPUR              114
EAST                  110
TOTAL DISTRICT(S)     110
BALRAMPUR             110
G.R.P.                106
Name: count, dtype: int64

In [201]:
print(df_long["Crime_Count"].sum())

3452727

In [207]:
df_long.to_csv(r"D:\Downloads\data\cleaned\ncrb_women_crimes_cleaned.csv",index=False)

In [208]:
print(os.listdir(r"D:\Downloads\data\cleaned"))

['crime_dataset_india_cleaned.csv', 'ncrb_women_crimes_cleaned.csv', 'police_stations_by_district_cleaned.csv']

In [209]:
df_long

                 State       District  Year Crime_Type  Crime_Count
0       ANDHRA PRADESH       ADILABAD  2001       RAPE           50
1       ANDHRA PRADESH      ANANTAPUR  2001       RAPE           23
2       ANDHRA PRADESH       CHITTOOR  2001       RAPE           27
3       ANDHRA PRADESH       CUDDAPAH  2001       RAPE           20
4       ANDHRA PRADESH  EAST GODAVARI  2001       RAPE           23
...                ...            ...   ...        ...          ...
58538  JAMMU & KASHMIR       UDHAMPUR  2020    ASSAULT           30
58539              NaN          TOTAL  2020    ASSAULT         1744
58540      LAKSHADWEEP    LAKSHADWEEP  2020    ASSAULT            3
58541              NaN          TOTAL  2020    ASSAULT            3
58542       PUDUCHERRY     PUDUCHERRY  2020    ASSAULT           25

[40897 rows x 5 columns]

The NCRB dataset was originally in a wide aggregated format, so we transformed it into a normalized long format using melting, 
filtered only women-safety-related crimes, and retained district- and year-level crime counts for analysis

In [ ]:
DATASET - 4

In [226]:
df_census = pd.read_csv("Final-censusdataset-India.csv")

In [227]:
df_census

,sr,state,District,person,Male,Female,growthinpopulation,rural,urban,urban.1,...,religion1 population,Religion2,Religion2 Population,religion3name,religion3poulation,inhabitadevillages,drinkingwater,electricity,primary school,Medical facility
0,1,ANdaman,"District Nicobars (01), Andaman & Nicobar Isla...",314084,170319,143765,30.14,197886,116198,844.0,...,235862,2.Christians,49033,3.Muslims,27134,331.0,331.0,233.0,185.0,102
1,2,ANdaman,"District Nicobars (02), Andaman & Nicobar Isla...",42068,22653,19415,7.19,42068,-,857.0,...,28145,2.Hindus,10727,3.Muslims,2131,170.0,169.0,96.0,53.0,38
2,3,Andhra,"District Adilabad (01), Andhra Pradesh (28)",2488003,1250958,1237045,19.06,1827986,NaN,989.0,...,2207843,NaN,236844,NaN,24392,1586.0,1585.0,1585.0,1521.0,976
3,4,Andhra,"District Nizamabad (02), Andhra Pradesh (28)",2345685,1162905,1182780,14.98,1920947,NaN,1017.0,...,1983275,2.Muslims,338824,3.Christians,16204,854.0,854.0,854.0,839.0,614
4,5,Andhra,"District Karimnagar (03), Andhra Pradesh (28)",3491822,1747968,1743854,14.47,2813010,NaN,998.0,...,3251834,2.Muslims,213811,3.Christians,20576,1047.0,1047.0,1047.0,1039.0,863
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
585,586,WestBengal,"District Puruliya (14), West Bengal (19)",2536516,1298078,1238438,13.96,2281090,NaN,954.0,...,2116037,2.Others,226912,3.Muslims,180694,2468.0,2452.0,1232.0,2135.0,1173
586,587,WestBengal,District Medinipur,9610788,4916370,4694418,15.68,8626883,NaN,955.0,...,8224779,2.Muslims,1088618,3.Others,262578,10548.0,10475.0,4835.0,6133.0,3560
587,588,WestBengal,District Haora,4273099,2241898,2031201,14.60,2121109,NaN,906.0,...,3204077,2.Muslims,1044383,3.Jains,9585,727.0,726.0,682.0,683.0,410
588,589,WestBengal,"District Kolkata (17), West Bengal (19)",4572876,2500040,2072836,4.11,-,NaN,829.0,...,3552274,2.Muslims,926769,3.Christians,40218,NaN,NaN,NaN,NaN,NaN
589,590,WestBengal,"Twenty Four Parganas (18), West Bengal (19)",6906689,3564993,3341696,20.89,5820469,NaN,937.0,...,4548459,NaN,2295967,NaN,52835,2087.0,2079.0,1322.0,1774.0,1311

In [228]:
df_census["District"].iloc[0]

'District Nicobars (01), Andaman & Nicobar Islands (35)'

In [229]:
df_census["District_clean"] = (
    df_census["District"]
    .astype(str)
    .str.replace("District", "", regex=False)
)

In [230]:
df_census["District_clean"].head(3)

0     Nicobars (01), Andaman & Nicobar Islands (35)
1     Nicobars (02), Andaman & Nicobar Islands (35)
2                Adilabad (01), Andhra Pradesh (28)
Name: District_clean, dtype: object

In [231]:
df_census["District_clean"] = (
    df_census["District_clean"]
    .str.split(r"\(|,", regex=True)
    .str[0]
    .str.strip()
    .str.upper()
)

In [232]:
df_census["District"] = df_census["District_clean"]
df_census.drop(columns=["District_clean"], inplace=True)

In [233]:
df_census["District"].head(10)

0        NICOBARS
1        NICOBARS
2        ADILABAD
3       NIZAMABAD
4      KARIMNAGAR
5           MEDAK
6       HYDERABAD
7    SECUNDARABAD
8     MAHBUBNAGAR
9        NALGONDA
Name: District, dtype: object

In [234]:
df_census["District"].isna().sum()

0

In [235]:
df_census["District"].nunique()

580

In [236]:
df_census[["state", "District"]].head(10)

     state      District
0  ANdaman      NICOBARS
1  ANdaman      NICOBARS
2   Andhra      ADILABAD
3   Andhra     NIZAMABAD
4   Andhra    KARIMNAGAR
5   Andhra         MEDAK
6   Andhra     HYDERABAD
7   Andhra  SECUNDARABAD
8   Andhra   MAHBUBNAGAR
9   Andhra      NALGONDA

The census dataset reflects administrative boundaries prior to the formation of Telangana (2014) and is used only for contextual demographic analysis,
not for current jurisdictional mapping.

In [237]:
df_census["District"] = df_census["District"].str.upper()

In [238]:
df_census["District"].head(5)

0      NICOBARS
1      NICOBARS
2      ADILABAD
3     NIZAMABAD
4    KARIMNAGAR
Name: District, dtype: object

In [239]:
df_census_clean = df_census[
    [
        "state",
        "District",
        "person",
        "Male",
        "Female",
        "urban",
        "rural",
        "Personlit_rate",
        "Flit_Rate"
    ]
]

In [240]:
df_census_clean

,state,District,person,Male,Female,urban,rural,Personlit_rate,Flit_Rate
0,ANdaman,NICOBARS,314084,170319,143765,116198,197886,82.49,76.62
1,ANdaman,NICOBARS,42068,22653,19415,-,42068,72.35,65.01
2,Andhra,ADILABAD,2488003,1250958,1237045,NaN,1827986,52.68,40.30
3,Andhra,NIZAMABAD,2345685,1162905,1182780,NaN,1920947,52.02,39.48
4,Andhra,KARIMNAGAR,3491822,1747968,1743854,NaN,2813010,54.90,42.75
...,...,...,...,...,...,...,...,...,...
585,WestBengal,PURULIYA,2536516,1298078,1238438,NaN,2281090,55.57,36.50
586,WestBengal,MEDINIPUR,9610788,4916370,4694418,NaN,8626883,74.90,64.42
587,WestBengal,HAORA,4273099,2241898,2031201,NaN,2121109,77.01,70.11
588,WestBengal,KOLKATA,4572876,2500040,2072836,NaN,-,80.86,77.30
589,WestBengal,TWENTY FOUR PARGANAS,6906689,3564993,3341696,NaN,5820469,69.45,59.01

In [241]:
df_census_clean.columns = [
    "State",
    "District",
    "Total_Population",
    "Male_Population",
    "Female_Population",
    "Urban_Population",
    "Rural_Population",
    "Literacy_Rate",
    "Female_Literacy_Rate"
]

In [242]:
df_census_clean.columns

Index(['State', 'District', 'Total_Population', 'Male_Population',
       'Female_Population', 'Urban_Population', 'Rural_Population',
       'Literacy_Rate', 'Female_Literacy_Rate'],
      dtype='object')

In [243]:
df_census_clean.head(5)

,State,District,Total_Population,Male_Population,Female_Population,Urban_Population,Rural_Population,Literacy_Rate,Female_Literacy_Rate
0,ANdaman,NICOBARS,314084,170319,143765,116198,197886,82.49,76.62
1,ANdaman,NICOBARS,42068,22653,19415,-,42068,72.35,65.01
2,Andhra,ADILABAD,2488003,1250958,1237045,NaN,1827986,52.68,40.30
3,Andhra,NIZAMABAD,2345685,1162905,1182780,NaN,1920947,52.02,39.48
4,Andhra,KARIMNAGAR,3491822,1747968,1743854,NaN,2813010,54.90,42.75

In [244]:
df_census_clean.to_csv(r"D:\Downloads\data\cleaned\census_india_cleaned.csv",index=False)

In [245]:
print(os.listdir(r"D:\Downloads\data\cleaned"))

['census_india_cleaned.csv', 'crime_dataset_india_cleaned.csv', 'ncrb_women_crimes_cleaned.csv', 'police_stations_by_district_cleaned.csv']

In [ ]:
DATASET - 5

In [247]:
import pandas as pd
import numpy as np
print("Libraries imported successfully")

Libraries imported successfully

In [249]:
df_5 = pd.read_csv("c8d3ea7e-4855-45f3-9c26-557419e93b6a.csv")

In [250]:
df_5

,_id,id,year,state_name,state_code,district_name,district_code,registration_circles,murder_with_rape_gang_rape,dowry_deaths,...,protection_of_women_from_domestic_violence,publshng_or_transmitting_of_sexually_explicit_mtrl,other_women_centric_cyber_crimes,child_rape,sexual_assault_of_children,child_sexual_harassment,use_of_child_for_pornography,offences_of_pocso_act,pocso_act_unnatural_offences,indecent_representation_of_women
0,1,0,2017,Andhra Pradesh,28,Ananthapuramu,502,Anantapur,0.0,14.0,...,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0
1,2,1,2017,Andhra Pradesh,28,Chittoor,503,Chittoor,0.0,8.0,...,0.0,0.0,0.0,6.0,2.0,1.0,0.0,0.0,0.0,0.0
2,3,2,2017,Andhra Pradesh,28,Y.S.R.,504,Cuddapah,0.0,15.0,...,0.0,1.0,0.0,15.0,2.0,3.0,0.0,0.0,1.0,0.0
3,4,3,2017,Andhra Pradesh,28,East Godavari,505,East Godavari,0.0,10.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
4,5,4,2017,Andhra Pradesh,28,Ananthapuramu,502,Guntakal Railway,0.0,3.0,...,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5317,5318,5317,2022,Jammu And Kashmir,1,Jammu,5,Special Crime Wing Kashmir,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5318,5319,5318,2022,Jammu And Kashmir,1,Srinagar,13,Anti Narcotic Task Force Kashmir,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5319,5320,5319,2022,Jammu And Kashmir,1,Jammu,5,Eow Jammu,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
5320,5321,5320,2022,Jammu And Kashmir,1,Srinagar,13,Eow Kashmir,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5321,5322,5321,2022,Jammu And Kashmir,1,Jammu,5,Cice Kashmir,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [268]:
df_5.shape

(5322, 50)

In [269]:
df_5.head()

,_id,id,year,state_name,state_code,district_name,district_code,registration_circles,murder_with_rape_gang_rape,dowry_deaths,...,protection_of_women_from_domestic_violence,publshng_or_transmitting_of_sexually_explicit_mtrl,other_women_centric_cyber_crimes,child_rape,sexual_assault_of_children,child_sexual_harassment,use_of_child_for_pornography,offences_of_pocso_act,pocso_act_unnatural_offences,indecent_representation_of_women
0,1,0,2017,Andhra Pradesh,28,Ananthapuramu,502,Anantapur,0.0,14.0,...,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0
1,2,1,2017,Andhra Pradesh,28,Chittoor,503,Chittoor,0.0,8.0,...,0.0,0.0,0.0,6.0,2.0,1.0,0.0,0.0,0.0,0.0
2,3,2,2017,Andhra Pradesh,28,Y.S.R.,504,Cuddapah,0.0,15.0,...,0.0,1.0,0.0,15.0,2.0,3.0,0.0,0.0,1.0,0.0
3,4,3,2017,Andhra Pradesh,28,East Godavari,505,East Godavari,0.0,10.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
4,5,4,2017,Andhra Pradesh,28,Ananthapuramu,502,Guntakal Railway,0.0,3.0,...,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0

In [270]:
df_5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5322 entries, 0 to 5321
Data columns (total 50 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   _id                                                       5322 non-null   int64
 1   id                                                        5322 non-null   int64
 2   year                                                      5322 non-null   int64
 3   state_name                                                5322 non-null   object
 4   state_code                                                5322 non-null   int64
 5   district_name                                             5322 non-null   object
 6   district_code                                             5322 non-null   int64
 7   registration_circles                                      5322 non-null   object
 8   murder_with_rape_gang_rape                                5322 non-null   float64
 9   dowry_deaths                                              5322 non-null   float64
 10  abetment_to_suicide_of_women                              5322 non-null   float64
 11  miscarriage                                               5322 non-null   float64
 12  acid_attack                                               5322 non-null   float64
 13  attempt_to_acid_attack                                    5322 non-null   float64
 14  cruelty_by_husband_or_his_relatives                       5322 non-null   float64
 15  kidnapping_and_abduction                                  5322 non-null   float64
 16  kidnapping_abduction_in_order_to_murder                   5322 non-null   float64
 17  kidnapping_for_ransom                                     1708 non-null   float64
 18  kidnp_and_abductn_of_women_above_18_for_marrg             5322 non-null   float64
 19  kidnp_and_abductn_of_girls_below_18_for_marrg             5322 non-null   float64
 20  procuration_of_minor_girls                                5322 non-null   float64
 21  importation_of_girls_from_foreign                         5322 non-null   float64
 22  kidnapping_and_abduction_of_women_others                  5322 non-null   float64
 23  human_trafficking                                         5322 non-null   float64
 24  selling_of_minor_girls                                    5322 non-null   float64
 25  buying_of_minor_girls                                     5322 non-null   float64
 26  rape_women_above_18                                       5322 non-null   float64
 27  rape_girls_below_18                                       5322 non-null   float64
 28  attempt_to_commit_rape_above_18                           5322 non-null   float64
 29  attempt_to_commit_rape_girls_below_18                     5322 non-null   float64
 30  assault_on_womenabove_18                                  5322 non-null   float64
 31  assault_on_women_below_18                                 5322 non-null   float64
 32  insult_to_the_modesty_of_women_above_18                   5322 non-null   float64
 33  insult_to_the_modesty_of_women_below_18                   5322 non-null   float64
 34  dowry_prohibition                                         5322 non-null   float64
 35  procuring_inducing_children_for_the_sake_of_prostitution  5322 non-null   float64
 36  detaining_a_prsn_in_premises_where_prost_is_carried       5322 non-null   float64
 37  prostitution_in_or_in_the_vicinity_of_public_places       5322 non-null   float64
 38  seducing_or_soliciting_for_purpose_of_prostitution        5322 non-null   float64
 39  other_sections_under_itp_act                              5322 non-null   float64
 40  protection_of_women_from_domestic_violence                5322 non-null   float64
 41  publshng_or_transmitting_of_sexually_explicit_mtrl        5322 non-null   float64
 42  other_women_centric_cyber_crimes                          5322 non-null   float64
 43  child_rape                                                5322 non-null   float64
 44  sexual_assault_of_children                                5322 non-null   float64
 45  child_sexual_harassment                                   5322 non-null   float64
 46  use_of_child_for_pornography                              5322 non-null   float64
 47  offences_of_pocso_act                                     5322 non-null   float64
 48  pocso_act_unnatural_offences                              5322 non-null   float64
 49  indecent_representation_of_women                          5322 non-null   float64
dtypes: float64(42), int64(5), object(3)
memory usage: 2.0+ MB

In [271]:
df_5.columns.tolist()

['_id',
 'id',
 'year',
 'state_name',
 'state_code',
 'district_name',
 'district_code',
 'registration_circles',
 'murder_with_rape_gang_rape',
 'dowry_deaths',
 'abetment_to_suicide_of_women',
 'miscarriage',
 'acid_attack',
 'attempt_to_acid_attack',
 'cruelty_by_husband_or_his_relatives',
 'kidnapping_and_abduction',
 'kidnapping_abduction_in_order_to_murder',
 'kidnapping_for_ransom',
 'kidnp_and_abductn_of_women_above_18_for_marrg',
 'kidnp_and_abductn_of_girls_below_18_for_marrg',
 'procuration_of_minor_girls',
 'importation_of_girls_from_foreign',
 'kidnapping_and_abduction_of_women_others',
 'human_trafficking',
 'selling_of_minor_girls',
 'buying_of_minor_girls',
 'rape_women_above_18',
 'rape_girls_below_18',
 'attempt_to_commit_rape_above_18',
 'attempt_to_commit_rape_girls_below_18',
 'assault_on_womenabove_18',
 'assault_on_women_below_18',
 'insult_to_the_modesty_of_women_above_18',
 'insult_to_the_modesty_of_women_below_18',
 'dowry_prohibition',
 'procuring_inducing_children_for_the_sake_of_prostitution',
 'detaining_a_prsn_in_premises_where_prost_is_carried',
 'prostitution_in_or_in_the_vicinity_of_public_places',
 'seducing_or_soliciting_for_purpose_of_prostitution',
 'other_sections_under_itp_act',
 'protection_of_women_from_domestic_violence',
 'publshng_or_transmitting_of_sexually_explicit_mtrl',
 'other_women_centric_cyber_crimes',
 'child_rape',
 'sexual_assault_of_children',
 'child_sexual_harassment',
 'use_of_child_for_pornography',
 'offences_of_pocso_act',
 'pocso_act_unnatural_offences',
 'indecent_representation_of_women']

In [275]:
df_5["state_name"] = df_5["state_name"].str.upper().str.strip()
df_5["district_name"] = df_5["district_name"].str.upper().str.strip()

In [276]:
df_5[["state_name", "district_name"]].head(10)

       state_name                district_name
0  ANDHRA PRADESH                ANANTHAPURAMU
1  ANDHRA PRADESH                     CHITTOOR
2  ANDHRA PRADESH                       Y.S.R.
3  ANDHRA PRADESH                EAST GODAVARI
4  ANDHRA PRADESH                ANANTHAPURAMU
5  ANDHRA PRADESH                       GUNTUR
6  ANDHRA PRADESH                       GUNTUR
7  ANDHRA PRADESH                      KRISHNA
8  ANDHRA PRADESH                      KURNOOL
9  ANDHRA PRADESH  SRI POTTI SRIRAMULU NELLORE

In [257]:
outdoor_crime_cols = [
    "rape_women_above_18",
    "rape_girls_below_18",
    "attempt_to_commit_rape_above_18",
    "attempt_to_commit_rape_girls_below_18",
    "sexual_assault_of_children",
    "assault_on_womenabove_18",
    "assault_on_women_below_18",
    "kidnapping_and_abduction",
    "kidnapping_for_ransom",
    "kidnapping_and_abduction_of_women_others",
    "human_trafficking",
    "procuration_of_minor_girls"
]

In [258]:
set(outdoor_crime_cols) - set(df.columns)

set()

In [279]:
df_5[outdoor_crime_cols] = (
    df_5[outdoor_crime_cols]
    .apply(pd.to_numeric, errors="coerce")
    .fillna(0)
    .astype(int)
)

In [278]:
df_5[outdoor_crime_cols].dtypes

rape_women_above_18                         float64
rape_girls_below_18                         float64
attempt_to_commit_rape_above_18             float64
attempt_to_commit_rape_girls_below_18       float64
sexual_assault_of_children                  float64
assault_on_womenabove_18                    float64
assault_on_women_below_18                   float64
kidnapping_and_abduction                    float64
kidnapping_for_ransom                       float64
kidnapping_and_abduction_of_women_others    float64
human_trafficking                           float64
procuration_of_minor_girls                  float64
dtype: object

In [280]:
df_5["outdoor_women_crime_total"] = df_5[outdoor_crime_cols].sum(axis=1)

In [281]:
df_5[["district_name", "outdoor_women_crime_total"]].head(10)

                 district_name  outdoor_women_crime_total
0                ANANTHAPURAMU                        510
1                     CHITTOOR                        210
2                       Y.S.R.                        562
3                EAST GODAVARI                        645
4                ANANTHAPURAMU                          5
5                       GUNTUR                        524
6                       GUNTUR                        207
7                      KRISHNA                        610
8                      KURNOOL                        408
9  SRI POTTI SRIRAMULU NELLORE                        396

In [282]:
#Remove Zero-Crime Rows (Noise Removal)
df_5 = df_5[df_5["outdoor_women_crime_total"] > 0]

In [283]:
df_5.shape

(5003, 51)

In [284]:
(df_5["outdoor_women_crime_total"] == 0).sum()

0

In [287]:
#Keep Only Relevant Columns (Clean Final Dataset)
final_cols = [
    "year",
    "state_name",
    "district_name",
    "outdoor_women_crime_total"
] + outdoor_crime_cols

df_5clean = df_5[final_cols].copy()

In [288]:
df_5clean.head()

,year,state_name,district_name,outdoor_women_crime_total,rape_women_above_18,rape_girls_below_18,attempt_to_commit_rape_above_18,attempt_to_commit_rape_girls_below_18,sexual_assault_of_children,assault_on_womenabove_18,assault_on_women_below_18,kidnapping_and_abduction,kidnapping_for_ransom,kidnapping_and_abduction_of_women_others,human_trafficking,procuration_of_minor_girls
0,2017,ANDHRA PRADESH,ANANTHAPURAMU,510,20,23,10,1,3,408,9,11,4,3,2,16
1,2017,ANDHRA PRADESH,CHITTOOR,210,6,18,4,5,2,163,5,5,0,0,0,2
2,2017,ANDHRA PRADESH,Y.S.R.,562,23,18,4,2,2,490,5,1,0,0,2,15
3,2017,ANDHRA PRADESH,EAST GODAVARI,645,19,89,9,3,1,465,42,10,0,1,0,6
4,2017,ANDHRA PRADESH,ANANTHAPURAMU,5,0,0,0,0,2,3,0,0,0,0,0,0

In [290]:
df_5clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5003 entries, 0 to 5315
Data columns (total 16 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   year                                      5003 non-null   int64
 1   state_name                                5003 non-null   object
 2   district_name                             5003 non-null   object
 3   outdoor_women_crime_total                 5003 non-null   int64
 4   rape_women_above_18                       5003 non-null   int32
 5   rape_girls_below_18                       5003 non-null   int32
 6   attempt_to_commit_rape_above_18           5003 non-null   int32
 7   attempt_to_commit_rape_girls_below_18     5003 non-null   int32
 8   sexual_assault_of_children                5003 non-null   int32
 9   assault_on_womenabove_18                  5003 non-null   int32
 10  assault_on_women_below_18                 5003 non-null   int32
 11  kidnapping_and_abduction                  5003 non-null   int32
 12  kidnapping_for_ransom                     5003 non-null   int32
 13  kidnapping_and_abduction_of_women_others  5003 non-null   int32
 14  human_trafficking                         5003 non-null   int32
 15  procuration_of_minor_girls                5003 non-null   int32
dtypes: int32(12), int64(2), object(2)
memory usage: 429.9+ KB

In [291]:
df_5clean.groupby("district_name")["outdoor_women_crime_total"] \
        .sum() \
        .sort_values(ascending=False) \
        .head(10)

district_name
MUMBAI               23750
PUNE                 15850
HYDERABAD            12534
NORTH 24 PARGANAS    12107
THANE                11624
NORTH WEST           11492
BENGALURU URBAN      10352
JAIPUR                9911
BALESHWAR             8585
SOUTH WEST            7436
Name: outdoor_women_crime_total, dtype: int64

In [292]:
df_5clean.groupby("state_name")["outdoor_women_crime_total"] \
        .sum() \
        .sort_values(ascending=False)

state_name
UTTAR PRADESH                                   138822
MAHARASHTRA                                     135561
MADHYA PRADESH                                  105815
RAJASTHAN                                       104474
ODISHA                                           99949
WEST BENGAL                                      67610
ASSAM                                            55151
DELHI                                            46529
KARNATAKA                                        44321
TELANGANA                                        43663
HARYANA                                          40694
ANDHRA PRADESH                                   39871
BIHAR                                            39153
KERALA                                           36146
CHHATTISGARH                                     29951
JHARKHAND                                        20425
PUNJAB                                           15780
GUJARAT                                          15176
JAMMU AND KASHMIR                                14340
TAMIL NADU                                       13473
UTTARAKHAND                                       8154
HIMACHAL PRADESH                                  6209
TRIPURA                                           2264
MEGHALAYA                                         1851
CHANDIGARH                                        1496
GOA                                               1430
ARUNACHAL PRADESH                                 1297
MANIPUR                                            936
MIZORAM                                            707
SIKKIM                                             445
ANDAMAN AND NICOBAR ISLANDS                        344
PUDUCHERRY                                         310
NAGALAND                                           195
THE DADRA AND NAGAR HAVELI AND DAMAN AND DIU       172
LAKSHADWEEP                                         95
LADAKH                                              26
Name: outdoor_women_crime_total, dtype: int64

In [293]:
df_5clean.groupby("year")["outdoor_women_crime_total"].sum()

year
2017    170896
2018    186229
2019    193166
2020    177752
2021    197635
2022    207157
Name: outdoor_women_crime_total, dtype: int64

In [299]:
df_5clean.to_csv(r"D:\Downloads\data\cleaned\cleaned_outdoor_women_crimes_2017.csv",index=False)
print("Saved successfully")

Saved successfully

In [296]:
df_5clean

,year,state_name,district_name,outdoor_women_crime_total,rape_women_above_18,rape_girls_below_18,attempt_to_commit_rape_above_18,attempt_to_commit_rape_girls_below_18,sexual_assault_of_children,assault_on_womenabove_18,assault_on_women_below_18,kidnapping_and_abduction,kidnapping_for_ransom,kidnapping_and_abduction_of_women_others,human_trafficking,procuration_of_minor_girls
0,2017,ANDHRA PRADESH,ANANTHAPURAMU,510,20,23,10,1,3,408,9,11,4,3,2,16
1,2017,ANDHRA PRADESH,CHITTOOR,210,6,18,4,5,2,163,5,5,0,0,0,2
2,2017,ANDHRA PRADESH,Y.S.R.,562,23,18,4,2,2,490,5,1,0,0,2,15
3,2017,ANDHRA PRADESH,EAST GODAVARI,645,19,89,9,3,1,465,42,10,0,1,0,6
4,2017,ANDHRA PRADESH,ANANTHAPURAMU,5,0,0,0,0,2,3,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5311,2022,TELANGANA,JAGITIAL,243,9,6,0,0,22,177,2,25,0,0,2,0
5312,2022,UTTAR PRADESH,FARRUKHABAD,259,15,34,8,23,56,38,0,85,0,0,0,0
5313,2022,UTTAR PRADESH,GAUTAM BUDDHA NAGAR,340,29,29,2,0,20,79,0,181,0,0,0,0
5314,2022,UTTARAKHAND,UDAM SINGH NAGAR,480,247,0,0,0,0,154,0,15,0,64,0,0
5315,2022,ANDAMAN AND NICOBAR ISLANDS,NORTH AND MIDDLE ANDAMAN,12,0,0,1,0,7,3,0,1,0,0,0,0

In [300]:
print(os.listdir(r"D:\Downloads\data\cleaned"))

['census_india_cleaned.csv', 'cleaned_outdoor_women_crimes_2017.csv', 'crime_dataset_india_cleaned.csv', 'ncrb_women_crimes_cleaned.csv', 'police_stations_by_district_cleaned.csv']

DATASET - 6

In [301]:
df_6 = pd.read_csv("Crime_Incidents_in_2024.csv")

In [302]:
df_6

,X,Y,CCN,REPORT_DAT,START_DATE,END_DATE,BLOCK,OFFENSE,METHOD,SHIFT,...,BLOCK_GROUP,CENSUS_TRACT,VOTING_PRECINCT,BID,XBLOCK,YBLOCK,LATITUDE,LONGITUDE,OBJECTID,OCTO_RECORD_ID
0,397229.10,138975.93,24183416,2024/11/25 23:49:02+00,2024/11/25 21:39:00+00,2024/11/25 22:27:00+00,2100 - 2199 BLOCK OF 14TH STREET NW,THEFT/OTHER,OTHERS,EVENING,...,004300 2,4300.0,Precinct 22,NaN,397229.10,138975.93,38.918649,-77.031952,853109661,NaN
1,399489.42,137252.09,24178148,2024/11/16 19:24:14+00,2024/11/13 16:00:00+00,2024/11/14 03:30:00+00,1000 - 1099 BLOCK OF 1ST STREET NE,THEFT F/AUTO,OTHERS,DAY,...,010603 3,10603.0,Precinct 144,NOMA,399489.42,137252.09,38.903124,-77.005886,853118108,NaN
2,400695.73,140731.99,24000256,2024/01/01 16:30:57+00,2024/01/01 03:00:00+00,2024/01/01 15:15:00+00,1000 - 1199 BLOCK OF OTIS STREET NE,MOTOR VEHICLE THEFT,OTHERS,DAY,...,009504 1,9504.0,Precinct 68,NaN,400695.73,140731.99,38.934472,-76.991976,853122284,NaN
3,397229.10,138975.93,24000758,2024/01/02 15:39:12+00,2024/01/02 14:30:00+00,2024/01/02 14:36:00+00,2100 - 2199 BLOCK OF 14TH STREET NW,THEFT/OTHER,OTHERS,DAY,...,004401 2,4401.0,Precinct 22,NaN,397229.10,138975.93,38.918649,-77.031952,853122285,NaN
4,398120.46,139391.23,24000781,2024/01/08 17:42:24+00,2024/01/02 15:19:00+00,2024/01/02 16:46:00+00,600 - 699 BLOCK OF HOWARD PLACE NW,THEFT/OTHER,OTHERS,DAY,...,007401 1,7401.0,Precinct 119,ANACOSTIA,398120.46,139391.23,38.922392,-77.021675,853122286,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29294,395405.92,139798.65,24174646,2024/11/10 05:06:18+00,2024/11/09 23:00:00+00,2024/11/09 23:10:00+00,2700 - 2798 BLOCK OF CONNECTICUT AVENUE NW,THEFT F/AUTO,OTHERS,MIDNIGHT,...,000501 1,501.0,Precinct 136,NaN,395405.92,139798.65,38.926052,-77.052981,853669318,NaN
29295,398858.52,138469.03,24174673,2024/11/10 06:42:59+00,2024/11/10 01:30:00+00,2024/11/10 06:35:00+00,100 - 199 BLOCK OF S STREET NW,MOTOR VEHICLE THEFT,OTHERS,MIDNIGHT,...,003302 1,3302.0,Precinct 19,NaN,398858.52,138469.03,38.914086,-77.013162,853669319,NaN
29296,397725.26,145077.24,24199370,2024/12/26 12:03:57+00,2024/12/26 03:00:00+00,2024/12/26 11:34:00+00,900 - 999 BLOCK OF BUTTERNUT STREET NW,THEFT F/AUTO,OTHERS,DAY,...,010300 3,10300.0,Precinct 63,NaN,397725.26,145077.24,38.973612,-77.026251,853669336,NaN
29297,395766.70,137555.93,24175547,2024/11/12 01:48:59+00,2024/11/11 23:33:00+00,2024/11/12 01:32:00+00,1200 - 1249 BLOCK OF 22ND STREET NW,THEFT/OTHER,OTHERS,EVENING,...,005501 1,5501.0,Precinct 4,NaN,395766.70,137555.93,38.905851,-77.048806,853669347,NaN
29298,394459.18,141888.04,24176093,2024/11/12 23:59:26+00,2024/11/12 21:28:00+00,2024/11/12 23:25:00+00,4227 - 4399 BLOCK OF CONNECTICUT AVENUE NW,THEFT/OTHER,OTHERS,EVENING,...,001303 1,1303.0,Precinct 34,NaN,394459.18,141888.04,38.944869,-77.063916,853669348,NaN

In [304]:
print("Shape:", df.shape)

Shape: (5003, 51)

In [305]:
print(df.columns.tolist())

['_id', 'id', 'year', 'state_name', 'state_code', 'district_name', 'district_code', 'registration_circles', 'murder_with_rape_gang_rape', 'dowry_deaths', 'abetment_to_suicide_of_women', 'miscarriage', 'acid_attack', 'attempt_to_acid_attack', 'cruelty_by_husband_or_his_relatives', 'kidnapping_and_abduction', 'kidnapping_abduction_in_order_to_murder', 'kidnapping_for_ransom', 'kidnp_and_abductn_of_women_above_18_for_marrg', 'kidnp_and_abductn_of_girls_below_18_for_marrg', 'procuration_of_minor_girls', 'importation_of_girls_from_foreign', 'kidnapping_and_abduction_of_women_others', 'human_trafficking', 'selling_of_minor_girls', 'buying_of_minor_girls', 'rape_women_above_18', 'rape_girls_below_18', 'attempt_to_commit_rape_above_18', 'attempt_to_commit_rape_girls_below_18', 'assault_on_womenabove_18', 'assault_on_women_below_18', 'insult_to_the_modesty_of_women_above_18', 'insult_to_the_modesty_of_women_below_18', 'dowry_prohibition', 'procuring_inducing_children_for_the_sake_of_prostitution', 'detaining_a_prsn_in_premises_where_prost_is_carried', 'prostitution_in_or_in_the_vicinity_of_public_places', 'seducing_or_soliciting_for_purpose_of_prostitution', 'other_sections_under_itp_act', 'protection_of_women_from_domestic_violence', 'publshng_or_transmitting_of_sexually_explicit_mtrl', 'other_women_centric_cyber_crimes', 'child_rape', 'sexual_assault_of_children', 'child_sexual_harassment', 'use_of_child_for_pornography', 'offences_of_pocso_act', 'pocso_act_unnatural_offences', 'indecent_representation_of_women', 'outdoor_women_crime_total']

In [307]:
df_6["OFFENSE"].value_counts().head(20)

OFFENSE
THEFT/OTHER                   13012
THEFT F/AUTO                   6685
MOTOR VEHICLE THEFT            5126
ROBBERY                        2110
ASSAULT W/DANGEROUS WEAPON     1028
BURGLARY                       1005
HOMICIDE                        187
SEX ABUSE                       142
ARSON                             4
Name: count, dtype: int64

In [309]:
columns_to_keep = [
    "CCN",
    "REPORT_DAT",
    "START_DATE",
    "END_DATE",
    "SHIFT",
    "OFFENSE",
    "BLOCK",
    "WARD",
    "DISTRICT",
    "NEIGHBORHOOD_CLUSTER",
    "LATITUDE",
    "LONGITUDE"
]

df_6 = df_6[columns_to_keep]

In [310]:
print(df_6.columns.tolist())

['CCN', 'REPORT_DAT', 'START_DATE', 'END_DATE', 'SHIFT', 'OFFENSE', 'BLOCK', 'WARD', 'DISTRICT', 'NEIGHBORHOOD_CLUSTER', 'LATITUDE', 'LONGITUDE']

In [314]:
df_6 = df_6.copy()
df_6["OFFENSE"] = df_6["OFFENSE"].str.upper().str.strip()

In [315]:
women_crime_keywords = [
    "ASSAULT",
    "SEXUAL",
    "RAPE",
    "KIDNAPPING",
    "HUMAN TRAFFICKING",
    "TRAFFICKING"
]

In [317]:
#Filter dataset to keep ONLY required crimes
pattern = "|".join(women_crime_keywords)

df_women = df_6[df_6["OFFENSE"].str.contains(pattern, na=False)]

In [318]:
#Remove non-relevant crimes that still contain keywords
exclude_keywords = [
    "THEFT",
    "ROBBERY",
    "BURGLARY",
    "MOTOR",
    "AUTO"
]

exclude_pattern = "|".join(exclude_keywords)

df_women = df_women[~df_women["OFFENSE"].str.contains(exclude_pattern, na=False)]

In [319]:
df_women["OFFENSE"].value_counts()

OFFENSE
ASSAULT W/DANGEROUS WEAPON    1028
Name: count, dtype: int64

In [320]:
#Convert date columns to datetime
date_cols = ["REPORT_DAT", "START_DATE", "END_DATE"]

for col in date_cols:
    df_women[col] = pd.to_datetime(df_women[col], errors="coerce")

In [321]:
#Remove rows without location
df_women = df_women.dropna(subset=["LATITUDE", "LONGITUDE"])

In [322]:
#Reset index
df_women.reset_index(drop=True, inplace=True)

In [323]:
#Extract time features
df_women["hour"] = df_women["START_DATE"].dt.hour
df_women["day"] = df_women["START_DATE"].dt.day
df_women["month"] = df_women["START_DATE"].dt.month
df_women["weekday"] = df_women["START_DATE"].dt.day_name()

In [324]:
#Night vs Day classification
def time_of_day(hour):
    if hour >= 20 or hour <= 5:
        return "Night"
    elif 6 <= hour <= 11:
        return "Morning"
    elif 12 <= hour <= 16:
        return "Afternoon"
    else:
        return "Evening"

df_women["time_period"] = df_women["hour"].apply(time_of_day)

In [325]:
#Crimes by type
df_women["OFFENSE"].value_counts()

OFFENSE
ASSAULT W/DANGEROUS WEAPON    1028
Name: count, dtype: int64

In [326]:
#Crimes by time period
df_women["time_period"].value_counts()

time_period
Night        588
Morning      175
Afternoon    140
Evening      125
Name: count, dtype: int64

In [327]:
#Crimes by ward
df_women["WARD"].value_counts().head(10)

WARD
8.0    339
7.0    238
5.0    134
1.0     83
4.0     82
2.0     72
6.0     63
3.0     16
Name: count, dtype: int64

This dataset records general urban crime incidents.
After filtering for women-related outdoor crimes using keyword-based semantic filtering, only Assault with Dangerous Weapon was present.
Other women-centric crimes such as rape, sexual assault, kidnapping, and trafficking were not available in this dataset, 
hence they do not appear in the filtered output.
This confirms both correct filtering logic and dataset limitation awareness.

In [328]:
#High-risk time periods
df_women.groupby("time_period").size().sort_values(ascending=False)

time_period
Night        588
Morning      175
Afternoon    140
Evening      125
dtype: int64

In [329]:
#High-risk locations
df_women.groupby("NEIGHBORHOOD_CLUSTER").size().sort_values(ascending=False).head(10)

NEIGHBORHOOD_CLUSTER
Cluster 39    131
Cluster 23     57
Cluster 34     54
Cluster 25     52
Cluster 2      51
Cluster 38     50
Cluster 32     49
Cluster 33     44
Cluster 37     43
Cluster 18     42
dtype: int64

In [330]:
#Save cleaned dataset
df_women.to_csv(r"D:\Downloads\data\cleaned\women_outdoor_crimes_2024_cleaned.csv",index=False)

In [331]:
df_women

,CCN,REPORT_DAT,START_DATE,END_DATE,SHIFT,OFFENSE,BLOCK,WARD,DISTRICT,NEIGHBORHOOD_CLUSTER,LATITUDE,LONGITUDE,hour,day,month,weekday,time_period
0,24001558,2024-01-04 02:09:24+00:00,2024-01-03 23:03:00+00:00,2024-01-04 00:26:00+00:00,EVENING,ASSAULT W/DANGEROUS WEAPON,1953 - 2099 BLOCK OF 19TH PLACE SE,8.0,7.0,Cluster 28,38.864664,-76.977529,23.0,3.0,1.0,Wednesday,Night
1,24019819,2024-02-08 04:29:10+00:00,2024-02-08 01:25:00+00:00,2024-02-09 03:30:00+00:00,MIDNIGHT,ASSAULT W/DANGEROUS WEAPON,3900 - 3999 BLOCK OF MARTIN LUTHER KING JR AVE...,8.0,7.0,Cluster 39,38.832561,-77.008997,1.0,8.0,2.0,Thursday,Night
2,24022148,2024-02-12 16:25:56+00:00,2024-02-12 15:30:00+00:00,2024-02-12 16:15:00+00:00,DAY,ASSAULT W/DANGEROUS WEAPON,1737 - 1776 BLOCK OF COLUMBIA ROAD NW,1.0,3.0,Cluster 1,38.923870,-77.040876,15.0,12.0,2.0,Monday,Afternoon
3,24005258,2024-01-11 13:51:09+00:00,2024-01-11 12:10:00+00:00,2024-01-11 12:15:00+00:00,DAY,ASSAULT W/DANGEROUS WEAPON,100 - 199 BLOCK OF ATLANTIC STREET SE,8.0,7.0,Cluster 39,38.831080,-77.004712,12.0,11.0,1.0,Thursday,Afternoon
4,24005185,2024-01-11 07:35:50+00:00,2024-01-11 04:56:00+00:00,2024-01-11 04:59:00+00:00,MIDNIGHT,ASSAULT W/DANGEROUS WEAPON,1000 - 1099 BLOCK OF WEBSTER STREET NW,4.0,4.0,Cluster 18,38.943993,-77.026703,4.0,11.0,1.0,Thursday,Night
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1023,24179007,2024-11-18 04:45:09+00:00,2024-11-18 02:38:00+00:00,2024-11-18 03:15:00+00:00,MIDNIGHT,ASSAULT W/DANGEROUS WEAPON,3200 - 3299 BLOCK OF MOUNT PLEASANT STREET NW,1.0,3.0,Cluster 2,38.931840,-77.038582,2.0,18.0,11.0,Monday,Night
1024,24016967,2024-02-03 01:03:11+00:00,2024-02-02 23:37:00+00:00,2024-02-03 01:03:00+00:00,EVENING,ASSAULT W/DANGEROUS WEAPON,1400 - 1499 BLOCK OF RHODE ISLAND AVENUE NW,2.0,2.0,Cluster 7,38.908382,-77.033254,23.0,2.0,2.0,Friday,Night
1025,24018397,2024-02-06 01:11:29+00:00,2024-02-05 20:39:00+00:00,2024-02-05 23:00:00+00:00,EVENING,ASSAULT W/DANGEROUS WEAPON,3900 - 3920 BLOCK OF 1ST STREET SE,8.0,7.0,Cluster 39,38.832551,-77.005885,20.0,5.0,2.0,Monday,Night
1026,24088908,2024-06-11 23:39:23+00:00,2024-06-11 20:22:00+00:00,2024-06-11 23:30:00+00:00,EVENING,ASSAULT W/DANGEROUS WEAPON,4000 - 4099 BLOCK OF KANSAS AVENUE NW,4.0,4.0,Cluster 18,38.940273,-77.027120,20.0,11.0,6.0,Tuesday,Night
1027,24168445,2024-10-30 09:14:00+00:00,2024-10-30 08:39:00+00:00,2024-10-30 10:00:00+00:00,MIDNIGHT,ASSAULT W/DANGEROUS WEAPON,81 - 199 BLOCK OF 55TH STREET SE,7.0,6.0,Cluster 33,38.887044,-76.922183,8.0,30.0,10.0,Wednesday,Morning

In [332]:
print(os.listdir(r"D:\Downloads\data\cleaned"))

['census_india_cleaned.csv', 'cleaned_outdoor_women_crimes_2017.csv', 'crime_dataset_india_cleaned.csv', 'ncrb_women_crimes_cleaned.csv', 'police_stations_by_district_cleaned.csv', 'women_outdoor_crimes_2024_cleaned.csv']

DATASET -7

In [333]:
import pandas as pd

df_7_raw = pd.read_csv("Crime against Women (2001-2022).csv")

In [334]:
df_7_raw

,CRIME HEAD,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Rape,16075,16373,15847,18233,18359,19348,20737,21467,21397,...,33707,36735,34651,38947,32559,33356,32033,28046,31677,31516
1,Kidnapping and Abduction of Women & Girls,14645,14506,13296,15578,15750,17414,20416,22939,25741,...,51881,57311,59277,64519,66333,72751,72780,62300,75369,85310
2,Dowry Deaths,6851,6822,6208,7026,6787,7618,8093,8172,8383,...,8233,8455,7634,7621,7466,7167,7115,6966,6753,6450
3,Assault on women with intent to outrage her mo...,34124,33943,32939,34567,34175,36617,38734,40413,38711,...,70739,82235,82422,84746,86001,89097,88367,85392,89200,83344
4,Insult to the modesty of Women,9746,10155,12325,10001,9984,9966,10950,12214,11009,...,12589,9735,8685,7305,7451,6992,6939,7065,7788,8972
5,Cruelty by Husband or his relatives,49170,49237,50703,58121,58319,63128,75930,81344,89546,...,118866,122877,123403,110378,104551,103272,125298,111549,136234,140019
6,Importation of Girls from Foreign Country,114,76,46,89,149,67,61,67,48,...,31,13,6,12,5,4,3,1,2,1
7,Immoral Traffic (P) Act,8796,6598,5510,5748,5908,4541,3568,2660,2474,...,2579,2617,2641,2337,2127,1882,1645,1294,1678,1497
8,Dowry Prohibition Act,3222,2816,2684,3592,3204,4504,5623,5555,5650,...,10709,10050,9894,9683,10189,12826,13297,10366,13568,13479
9,Indecent Representation of Women (P) Act,1052,2508,1043,1378,2917,1562,1200,1025,845,...,362,47,40,38,25,22,23,12,28,28
10,Total Crimes against Women,143795,143034,140601,154333,155552,164765,185312,195856,203804,...,309696,330075,328653,325586,316707,327369,347500,312991,362297,370616

In [336]:

df_7_raw.columns.tolist()

['CRIME HEAD',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021',
 '2022']

In [337]:
df_7_raw.shape

(11, 23)

In [338]:
df_7_raw["CRIME HEAD"] = (
    df_7_raw["CRIME HEAD"]
    .str.upper()
    .str.strip()
)

In [339]:
df_7_raw["CRIME HEAD"]

0                                                  RAPE
1             KIDNAPPING AND ABDUCTION OF WOMEN & GIRLS
2                                          DOWRY DEATHS
3     ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MO...
4                        INSULT TO THE MODESTY OF WOMEN
5                   CRUELTY BY HUSBAND OR HIS RELATIVES
6             IMPORTATION OF GIRLS FROM FOREIGN COUNTRY
7                               IMMORAL TRAFFIC (P) ACT
8                                 DOWRY PROHIBITION ACT
9              INDECENT REPRESENTATION OF WOMEN (P) ACT
10                           TOTAL CRIMES AGAINST WOMEN
Name: CRIME HEAD, dtype: object

In [341]:

#Only outdoor / public women-related crimes:

women_crime_keywords = [
    "RAPE",
    "KIDNAPPING",
    "ABDUCTION",
    "ASSAULT",
    "TRAFFIC",
    "TRAFFICK",
    "IMMORAL TRAFFIC"
]

In [343]:
#Filter ONLY required women-related crimes
pattern = "|".join(women_crime_keywords)

df_7_women = df_7_raw[
    df_7_raw["CRIME HEAD"].str.contains(pattern, na=False)
].copy()

In [344]:
df_7_women["CRIME HEAD"]

0                                                 RAPE
1            KIDNAPPING AND ABDUCTION OF WOMEN & GIRLS
3    ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MO...
7                              IMMORAL TRAFFIC (P) ACT
Name: CRIME HEAD, dtype: object

In [346]:
df_7_women.shape

(4, 23)

In [345]:
df_7_women.head()

,CRIME HEAD,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,RAPE,16075,16373,15847,18233,18359,19348,20737,21467,21397,...,33707,36735,34651,38947,32559,33356,32033,28046,31677,31516
1,KIDNAPPING AND ABDUCTION OF WOMEN & GIRLS,14645,14506,13296,15578,15750,17414,20416,22939,25741,...,51881,57311,59277,64519,66333,72751,72780,62300,75369,85310
3,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MO...,34124,33943,32939,34567,34175,36617,38734,40413,38711,...,70739,82235,82422,84746,86001,89097,88367,85392,89200,83344
7,IMMORAL TRAFFIC (P) ACT,8796,6598,5510,5748,5908,4541,3568,2660,2474,...,2579,2617,2641,2337,2127,1882,1645,1294,1678,1497

In [347]:
#Convert wide format → long format
df_7_long = df_7_women.melt(
    id_vars="CRIME HEAD",
    var_name="YEAR",
    value_name="CRIME_COUNT"
)

In [352]:
df_7_long

                                           CRIME HEAD  YEAR  CRIME_COUNT
0                                                RAPE  2001        16075
1           KIDNAPPING AND ABDUCTION OF WOMEN & GIRLS  2001        14645
2   ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MO...  2001        34124
3                             IMMORAL TRAFFIC (P) ACT  2001         8796
4                                                RAPE  2002        16373
..                                                ...   ...          ...
83                            IMMORAL TRAFFIC (P) ACT  2021         1678
84                                               RAPE  2022        31516
85          KIDNAPPING AND ABDUCTION OF WOMEN & GIRLS  2022        85310
86  ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MO...  2022        83344
87                            IMMORAL TRAFFIC (P) ACT  2022         1497

[88 rows x 3 columns]

In [348]:
df_7_long.dtypes

CRIME HEAD     object
YEAR           object
CRIME_COUNT     int64
dtype: object

In [349]:
df_7_long.isna().sum()

CRIME HEAD     0
YEAR           0
CRIME_COUNT    0
dtype: int64

In [350]:
df_7_long["CRIME HEAD"].value_counts()

CRIME HEAD
RAPE                                                   22
KIDNAPPING AND ABDUCTION OF WOMEN & GIRLS              22
ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY    22
IMMORAL TRAFFIC (P) ACT                                22
Name: count, dtype: int64

In [351]:
df_7_long.head(10)

                                          CRIME HEAD  YEAR  CRIME_COUNT
0                                               RAPE  2001        16075
1          KIDNAPPING AND ABDUCTION OF WOMEN & GIRLS  2001        14645
2  ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MO...  2001        34124
3                            IMMORAL TRAFFIC (P) ACT  2001         8796
4                                               RAPE  2002        16373
5          KIDNAPPING AND ABDUCTION OF WOMEN & GIRLS  2002        14506
6  ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MO...  2002        33943
7                            IMMORAL TRAFFIC (P) ACT  2002         6598
8                                               RAPE  2003        15847
9          KIDNAPPING AND ABDUCTION OF WOMEN & GIRLS  2003        13296

In [358]:

df_7_long.groupby("YEAR")["CRIME_COUNT"].sum().head(10)

YEAR
2001    73640
2002    71420
2003    67592
2004    74126
2005    74192
2006    77920
2007    83455
2008    87479
2009    88323
2010    95079
Name: CRIME_COUNT, dtype: int64

In [359]:
df_7_long[
    df_7_long["CRIME HEAD"] == "RAPE"
].sort_values("YEAR").head(10)

   CRIME HEAD  YEAR  CRIME_COUNT
0        RAPE  2001        16075
4        RAPE  2002        16373
8        RAPE  2003        15847
12       RAPE  2004        18233
16       RAPE  2005        18359
20       RAPE  2006        19348
24       RAPE  2007        20737
28       RAPE  2008        21467
32       RAPE  2009        21397
36       RAPE  2010        22172

In [353]:
df_7_long.to_csv(r"D:\Downloads\data\cleaned\crime_against_women_trend_cleaned.csv",index=False)

In [356]:
import os
os.listdir(r"D:\Downloads\data\cleaned")

['census_india_cleaned.csv',
 'cleaned_outdoor_women_crimes_2017.csv',
 'crime_against_women_trend_cleaned.csv',
 'crime_dataset_india_cleaned.csv',
 'ncrb_women_crimes_cleaned.csv',
 'police_stations_by_district_cleaned.csv',
 'women_outdoor_crimes_2024_cleaned.csv']

In [360]:
df_7_long

                                           CRIME HEAD  YEAR  CRIME_COUNT
0                                                RAPE  2001        16075
1           KIDNAPPING AND ABDUCTION OF WOMEN & GIRLS  2001        14645
2   ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MO...  2001        34124
3                             IMMORAL TRAFFIC (P) ACT  2001         8796
4                                                RAPE  2002        16373
..                                                ...   ...          ...
83                            IMMORAL TRAFFIC (P) ACT  2021         1678
84                                               RAPE  2022        31516
85          KIDNAPPING AND ABDUCTION OF WOMEN & GIRLS  2022        85310
86  ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MO...  2022        83344
87                            IMMORAL TRAFFIC (P) ACT  2022         1497

[88 rows x 3 columns]

DATASET -8

In [362]:
import pandas as pd

df_8_raw = pd.read_csv("RS-Session-251-AS201-Table1.csv")

In [363]:
df_8_raw

                                            Heads   2016  2017  2018
0                      Number of women trafficked   5239  2040  2472
1                   Number of children trafficked   9034  3535  2834
2  Number of women victims of trafficking rescued   7238  2211  2493
3  Number of child victims of trafficking rescued  14183  3294  2358

In [387]:
df_8_raw.dtypes

Heads    object
2016      int64
2017      int64
2018      int64
dtype: object

In [388]:
df_8 = df_8_raw.copy()

In [389]:
df_8.head()

                                            Heads   2016  2017  2018
0                      Number of women trafficked   5239  2040  2472
1                   Number of children trafficked   9034  3535  2834
2  Number of women victims of trafficking rescued   7238  2211  2493
3  Number of child victims of trafficking rescued  14183  3294  2358

In [390]:
df_8.loc[:, "Heads"] = (
    df_8["Heads"]
    .astype(str)
    .str.upper()
    .str.strip()
)

In [391]:
df_8["Heads"].unique()

array(['NUMBER OF WOMEN TRAFFICKED', 'NUMBER OF CHILDREN TRAFFICKED',
       'NUMBER OF WOMEN VICTIMS OF TRAFFICKING RESCUED',
       'NUMBER OF CHILD VICTIMS OF TRAFFICKING RESCUED'], dtype=object)

In [392]:
#Convert year columns to numeric
year_cols = ["2016", "2017", "2018"]

df_8[year_cols] = df_8[year_cols].apply(
    pd.to_numeric, errors="coerce"
)

In [393]:
df_8.dtypes

Heads    object
2016      int64
2017      int64
2018      int64
dtype: object

In [375]:
#Define combined pattern
trafficking_pattern = "WOMEN|CHILD"

In [397]:
df_8_wc = df_8[
    df_8["Heads"].str.contains(
        trafficking_pattern,
        na=False,
        regex=True
    )
].copy()

In [398]:
df_8_wc

                                            Heads   2016  2017  2018
0                      NUMBER OF WOMEN TRAFFICKED   5239  2040  2472
1                   NUMBER OF CHILDREN TRAFFICKED   9034  3535  2834
2  NUMBER OF WOMEN VICTIMS OF TRAFFICKING RESCUED   7238  2211  2493
3  NUMBER OF CHILD VICTIMS OF TRAFFICKING RESCUED  14183  3294  2358

In [399]:
df_8_long = df_8_wc.melt(
    id_vars="Heads",
    value_vars=year_cols,
    var_name="Year",
    value_name="Count"
)

In [400]:

df_8_long.shape

(12, 3)

In [401]:
df_8_long.head()

                                            Heads  Year  Count
0                      NUMBER OF WOMEN TRAFFICKED  2016   5239
1                   NUMBER OF CHILDREN TRAFFICKED  2016   9034
2  NUMBER OF WOMEN VICTIMS OF TRAFFICKING RESCUED  2016   7238
3  NUMBER OF CHILD VICTIMS OF TRAFFICKING RESCUED  2016  14183
4                      NUMBER OF WOMEN TRAFFICKED  2017   2040

In [402]:
#Year-wise trafficking trend (women + children)
df_8_long.groupby("Year")["Count"].sum()

Year
2016    35694
2017    11080
2018    10157
Name: Count, dtype: int64

In [403]:
#Category-wise totals
df_8_long.groupby("Heads")["Count"].sum()

Heads
NUMBER OF CHILD VICTIMS OF TRAFFICKING RESCUED    19835
NUMBER OF CHILDREN TRAFFICKED                     15403
NUMBER OF WOMEN TRAFFICKED                         9751
NUMBER OF WOMEN VICTIMS OF TRAFFICKING RESCUED    11942
Name: Count, dtype: int64

In [404]:
df_8_long.describe()

              Count
count     12.000000
mean    4744.250000
std     3702.896265
min     2040.000000
25%     2443.500000
50%     3064.000000
75%     5738.750000
max    14183.000000

In [405]:
df_8_long

                                             Heads  Year  Count
0                       NUMBER OF WOMEN TRAFFICKED  2016   5239
1                    NUMBER OF CHILDREN TRAFFICKED  2016   9034
2   NUMBER OF WOMEN VICTIMS OF TRAFFICKING RESCUED  2016   7238
3   NUMBER OF CHILD VICTIMS OF TRAFFICKING RESCUED  2016  14183
4                       NUMBER OF WOMEN TRAFFICKED  2017   2040
5                    NUMBER OF CHILDREN TRAFFICKED  2017   3535
6   NUMBER OF WOMEN VICTIMS OF TRAFFICKING RESCUED  2017   2211
7   NUMBER OF CHILD VICTIMS OF TRAFFICKING RESCUED  2017   3294
8                       NUMBER OF WOMEN TRAFFICKED  2018   2472
9                    NUMBER OF CHILDREN TRAFFICKED  2018   2834
10  NUMBER OF WOMEN VICTIMS OF TRAFFICKING RESCUED  2018   2493
11  NUMBER OF CHILD VICTIMS OF TRAFFICKING RESCUED  2018   2358

In [406]:
df_8_long.to_csv(r"D:\Downloads\data\cleaned\women_children_crimedata_cleaned.csv",index=False)

In [407]:
import os
os.listdir(r"D:\Downloads\data\cleaned")

['census_india_cleaned.csv',
 'cleaned_outdoor_women_crimes_2017.csv',
 'crime_against_women_trend_cleaned.csv',
 'crime_dataset_india_cleaned.csv',
 'ncrb_women_crimes_cleaned.csv',
 'police_stations_by_district_cleaned.csv',
 'women_children_crimedata_cleaned.csv',
 'women_outdoor_crimes_2024_cleaned.csv']

In [1]:
import pandas as pd
import numpy as np

In [5]:
file_paths = [
    r"D:\Downloads\data\cleaned\women_children_crimedata_cleaned.csv",
    r"D:\Downloads\data\cleaned\crime_against_women_trend_cleaned.csv",
    r"D:\Downloads\data\cleaned\women_outdoor_crimes_2024_cleaned.csv",
    r"D:\Downloads\data\cleaned\cleaned_outdoor_women_crimes_2017.csv",
    r"D:\Downloads\data\cleaned\census_india_cleaned.csv",
    r"D:\Downloads\data\cleaned\ncrb_women_crimes_cleaned.csv",
    r"D:\Downloads\data\cleaned\police_stations_by_district_cleaned.csv",
    r"D:\Downloads\data\cleaned\crime_dataset_india_cleaned.csv"
]

dfs = []
for f in file_paths:
    df = pd.read_csv(f)
    print(f"Loaded {f} → {df.shape}")
    dfs.append(df)

Loaded D:\Downloads\data\cleaned\women_children_crimedata_cleaned.csv → (12, 3)
Loaded D:\Downloads\data\cleaned\crime_against_women_trend_cleaned.csv → (88, 3)
Loaded D:\Downloads\data\cleaned\women_outdoor_crimes_2024_cleaned.csv → (1028, 17)
Loaded D:\Downloads\data\cleaned\cleaned_outdoor_women_crimes_2017.csv → (5003, 16)
Loaded D:\Downloads\data\cleaned\census_india_cleaned.csv → (590, 9)
Loaded D:\Downloads\data\cleaned\ncrb_women_crimes_cleaned.csv → (40897, 5)
Loaded D:\Downloads\data\cleaned\police_stations_by_district_cleaned.csv → (31, 2)
Loaded D:\Downloads\data\cleaned\crime_dataset_india_cleaned.csv → (3201, 7)

In [8]:
def normalize_columns(df):
    df.columns = (
        df.columns
        .str.lower()
        .str.strip()
        .str.replace(" ", "_")
    )
    return df

dfs = [normalize_columns(df) for df in dfs]

In [ ]:
rename_candidates = {
    "crime_head": "crime_type",
    "offense": "crime_type",
    "offence": "crime_type",

    "district_name": "district",
    "state_name": "state",

    "lat": "latitude",
    "lon": "longitude",
    "long": "longitude",

    "year_reported": "year"
}

standardized_dfs = []

for df in dfs:
    cols = df.columns.tolist()
    rename_map = {k: v for k, v in rename_candidates.items() if k in cols}
    standardized_dfs.append(df.rename(columns=rename_map))

dfs = standardized_dfs

In [10]:
outdoor_2024 = pd.read_csv(r"D:\Downloads\data\cleaned\women_outdoor_crimes_2024_cleaned.csv")
ncrb = pd.read_csv(r"D:\Downloads\data\cleaned\ncrb_women_crimes_cleaned.csv")
outdoor_2017 = pd.read_csv(r"D:\Downloads\data\cleaned\cleaned_outdoor_women_crimes_2017.csv")
trend = pd.read_csv(r"D:\Downloads\data\cleaned\crime_against_women_trend_cleaned.csv")
women_children = pd.read_csv(r"D:\Downloads\data\cleaned\women_children_crimedata_cleaned.csv")

In [11]:
def normalize(df):
    df.columns = (
        df.columns.str.lower()
        .str.strip()
        .str.replace(" ", "_")
    )
    return df

datasets = [outdoor_2024, ncrb, outdoor_2017, trend, women_children]
datasets = [normalize(df) for df in datasets]

outdoor_2024, ncrb, outdoor_2017, trend, women_children = datasets

In [12]:
rename_map = {
    "offense": "crime_type",
    "crime_head": "crime_type",
    "district_name": "district",
    "state_name": "state",
    "lat": "latitude",
    "lon": "longitude",
    "long": "longitude",
    "hour": "crime_hour",
    "time_period": "day_night"
}

def rename_columns(df):
    return df.rename(columns={k:v for k,v in rename_map.items() if k in df.columns})

outdoor_2024 = rename_columns(outdoor_2024)
ncrb = rename_columns(ncrb)
outdoor_2017 = rename_columns(outdoor_2017)
trend = rename_columns(trend)
women_children = rename_columns(women_children)

In [14]:
print(outdoor_2017.columns.tolist())

['year', 'state', 'district', 'outdoor_women_crime_total', 'rape_women_above_18', 'rape_girls_below_18', 'attempt_to_commit_rape_above_18', 'attempt_to_commit_rape_girls_below_18', 'sexual_assault_of_children', 'assault_on_womenabove_18', 'assault_on_women_below_18', 'kidnapping_and_abduction', 'kidnapping_for_ransom', 'kidnapping_and_abduction_of_women_others', 'human_trafficking', 'procuration_of_minor_girls']

In [15]:
crime_cols = [
    c for c in outdoor_2017.columns
    if c not in ["state", "district", "year"]
]

In [16]:
outdoor_2017_long = outdoor_2017.melt(
    id_vars=["state", "district", "year"],
    value_vars=crime_cols,
    var_name="crime_type",
    value_name="crime_count"
)

In [17]:
outdoor_2017_long = outdoor_2017_long[outdoor_2017_long["crime_count"] > 0]

In [18]:
outdoor_2017_long.head()

            state       district  year                 crime_type  crime_count
0  ANDHRA PRADESH  ANANTHAPURAMU  2017  outdoor_women_crime_total          510
1  ANDHRA PRADESH       CHITTOOR  2017  outdoor_women_crime_total          210
2  ANDHRA PRADESH         Y.S.R.  2017  outdoor_women_crime_total          562
3  ANDHRA PRADESH  EAST GODAVARI  2017  outdoor_women_crime_total          645
4  ANDHRA PRADESH  ANANTHAPURAMU  2017  outdoor_women_crime_total            5

In [19]:
outdoor_2017_long.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31254 entries, 0 to 65032
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   state        31254 non-null  object
 1   district     31254 non-null  object
 2   year         31254 non-null  int64
 3   crime_type   31254 non-null  object
 4   crime_count  31254 non-null  int64
dtypes: int64(2), object(3)
memory usage: 1.4+ MB

In [20]:
ncrb_final = ncrb[[
    "state", "district", "year",
    "crime_type", "crime_count"
]]

In [22]:
outdoor_2024_final = outdoor_2024[
    [
        "district", "crime_type",
        "crime_hour", "day_night",
        "latitude", "longitude",
        "month", "weekday"
    ]
].copy()

outdoor_2024_final["year"] = 2024
outdoor_2024_final["crime_count"] = 1
outdoor_2024_final["state"] = "UNKNOWN"

In [23]:
final_df = pd.concat(
    [ncrb_final, outdoor_2017_long, outdoor_2024_final],
    ignore_index=True
)

In [24]:
final_df["victim_gender"] = "Female"
final_df["victim_age_group"] = "Unknown"
final_df["women_flag"] = 1

In [25]:
def category(ct):
    ct = str(ct).upper()
    if "RAPE" in ct or "TRAFFICK" in ct:
        return "Severe"
    elif "ASSAULT" in ct or "KIDNAP" in ct:
        return "Moderate"
    else:
        return "Low"

final_df["crime_category"] = final_df["crime_type"].apply(category)
final_df["crime_severity"] = final_df["crime_category"]

In [26]:
final_df["public_space_flag"] = final_df["crime_type"].str.contains(
    "STREET|PUBLIC|ROAD|OUTDOOR", case=False, na=False
).astype(int)

In [27]:
final_df = final_df.drop_duplicates(
    subset=["state", "district", "crime_type", "year"]
)

In [28]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 59810 entries, 0 to 72217
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   state              59804 non-null  object
 1   district           59804 non-null  object
 2   year               59810 non-null  int64
 3   crime_type         59810 non-null  object
 4   crime_count        59810 non-null  int64
 5   crime_hour         8 non-null      float64
 6   day_night          8 non-null      object
 7   latitude           8 non-null      float64
 8   longitude          8 non-null      float64
 9   month              8 non-null      float64
 10  weekday            8 non-null      object
 11  victim_gender      59810 non-null  object
 12  victim_age_group   59810 non-null  object
 13  women_flag         59810 non-null  int64
 14  crime_category     59810 non-null  object
 15  crime_severity     59810 non-null  object
 16  public_space_flag  59810 non-null  int32
dtypes: float64(4), int32(1), int64(3), object(9)
memory usage: 8.0+ MB

In [29]:
final_df.head()

,state,district,year,crime_type,crime_count,crime_hour,day_night,latitude,longitude,month,weekday,victim_gender,victim_age_group,women_flag,crime_category,crime_severity,public_space_flag
0,ANDHRA PRADESH,ADILABAD,2001,RAPE,50,NaN,NaN,NaN,NaN,NaN,NaN,Female,Unknown,1,Severe,Severe,0
1,ANDHRA PRADESH,ANANTAPUR,2001,RAPE,23,NaN,NaN,NaN,NaN,NaN,NaN,Female,Unknown,1,Severe,Severe,0
2,ANDHRA PRADESH,CHITTOOR,2001,RAPE,27,NaN,NaN,NaN,NaN,NaN,NaN,Female,Unknown,1,Severe,Severe,0
3,ANDHRA PRADESH,CUDDAPAH,2001,RAPE,20,NaN,NaN,NaN,NaN,NaN,NaN,Female,Unknown,1,Severe,Severe,0
4,ANDHRA PRADESH,EAST GODAVARI,2001,RAPE,23,NaN,NaN,NaN,NaN,NaN,NaN,Female,Unknown,1,Severe,Severe,0

In [30]:
time_cols = ["crime_hour", "day_night", "month", "weekday"]

final_df[time_cols] = final_df[time_cols].fillna("Unknown")

In [31]:
geo_cols = ["latitude", "longitude"]

final_df[geo_cols] = final_df[geo_cols].fillna("Not Available")

In [32]:
final_df["crime_count"] = pd.to_numeric(final_df["crime_count"], errors="coerce")
final_df["year"] = pd.to_numeric(final_df["year"], errors="coerce")

In [33]:
final_df.isnull().sum()

state                6
district             6
year                 0
crime_type           0
crime_count          0
crime_hour           0
day_night            0
latitude             0
longitude            0
month                0
weekday              0
victim_gender        0
victim_age_group     0
women_flag           0
crime_category       0
crime_severity       0
public_space_flag    0
dtype: int64

In [34]:
final_df.head()

,state,district,year,crime_type,crime_count,crime_hour,day_night,latitude,longitude,month,weekday,victim_gender,victim_age_group,women_flag,crime_category,crime_severity,public_space_flag
0,ANDHRA PRADESH,ADILABAD,2001,RAPE,50,Unknown,Unknown,Not Available,Not Available,Unknown,Unknown,Female,Unknown,1,Severe,Severe,0
1,ANDHRA PRADESH,ANANTAPUR,2001,RAPE,23,Unknown,Unknown,Not Available,Not Available,Unknown,Unknown,Female,Unknown,1,Severe,Severe,0
2,ANDHRA PRADESH,CHITTOOR,2001,RAPE,27,Unknown,Unknown,Not Available,Not Available,Unknown,Unknown,Female,Unknown,1,Severe,Severe,0
3,ANDHRA PRADESH,CUDDAPAH,2001,RAPE,20,Unknown,Unknown,Not Available,Not Available,Unknown,Unknown,Female,Unknown,1,Severe,Severe,0
4,ANDHRA PRADESH,EAST GODAVARI,2001,RAPE,23,Unknown,Unknown,Not Available,Not Available,Unknown,Unknown,Female,Unknown,1,Severe,Severe,0

In [35]:
ncrb_final["data_source"] = "AGGREGATED"
outdoor_2017_long["data_source"] = "AGGREGATED"
outdoor_2024_final["data_source"] = "EVENT"

In [36]:
final_df = pd.concat(
    [ncrb_final, outdoor_2017_long, outdoor_2024_final],
    ignore_index=True
)

In [38]:
numeric_time_cols = ["crime_hour", "month"]
categorical_time_cols = ["day_night", "weekday"]

In [39]:
final_df.loc[
    final_df["data_source"] == "AGGREGATED",
    numeric_time_cols
] = final_df.loc[
    final_df["data_source"] == "AGGREGATED",
    numeric_time_cols
].fillna(-1)

In [40]:
final_df.loc[
    final_df["data_source"] == "AGGREGATED",
    categorical_time_cols
] = final_df.loc[
    final_df["data_source"] == "AGGREGATED",
    categorical_time_cols
].fillna("All")

In [41]:
final_df.loc[
    final_df["data_source"] == "AGGREGATED",
    ["latitude", "longitude"]
] = final_df.loc[
    final_df["data_source"] == "AGGREGATED",
    ["latitude", "longitude"]
]

In [42]:
final_df.dtypes

state           object
district        object
year             int64
crime_type      object
crime_count      int64
data_source     object
crime_hour      object
day_night       object
latitude       float64
longitude      float64
month           object
weekday         object
dtype: object

In [43]:
final_df.head()

,state,district,year,crime_type,crime_count,data_source,crime_hour,day_night,latitude,longitude,month,weekday
0,ANDHRA PRADESH,ADILABAD,2001,RAPE,50,AGGREGATED,All,All,NaN,NaN,All,All
1,ANDHRA PRADESH,ANANTAPUR,2001,RAPE,23,AGGREGATED,All,All,NaN,NaN,All,All
2,ANDHRA PRADESH,CHITTOOR,2001,RAPE,27,AGGREGATED,All,All,NaN,NaN,All,All
3,ANDHRA PRADESH,CUDDAPAH,2001,RAPE,20,AGGREGATED,All,All,NaN,NaN,All,All
4,ANDHRA PRADESH,EAST GODAVARI,2001,RAPE,23,AGGREGATED,All,All,NaN,NaN,All,All

In [4]:
import pandas as pd
import numpy as np

# Load Dataset 1
df = pd.read_csv(r"D:\Downloads\data\cleaned\crime_dataset_india_cleaned.csv")

# Normalize column names
df.columns = df.columns.str.strip().str.lower()

In [5]:
print(df.shape)

(3201, 7)

In [6]:
print(df.columns.tolist())

['area', 'crime_type', 'year', 'crime_count', 'crime_date', 'crime_hour', 'day_night']

In [9]:
df["crime_date"] = pd.to_datetime(df["crime_date"], errors="coerce")

df["crime_hour"] = (
    pd.to_numeric(df["crime_hour"], errors="coerce")
    .fillna(0)
    .astype(int)
)

In [10]:
print(df[["crime_date", "crime_hour"]].head())

           crime_date  crime_hour
0 2020-01-01 02:00:00          14
1 2020-01-01 14:00:00          22
2 2020-01-02 12:00:00           0
3 2020-01-03 08:00:00          20
4 2020-01-03 09:00:00           9

In [11]:
critical_cols = [
    "area",
    "crime_type",
    "year",
    "crime_count",
    "crime_date",
    "crime_hour",
    "day_night"
]

In [13]:
df = df.dropna(subset=critical_cols)

In [14]:
print(df.isnull().sum())

area           0
crime_type     0
year           0
crime_count    0
crime_date     0
crime_hour     0
day_night      0
dtype: int64

In [15]:
assert df.isnull().sum().sum() == 0
print("DATASET CLEAN — NO NULL VALUES")

DATASET CLEAN — NO NULL VALUES

In [16]:
df["crime_date"] = pd.to_datetime(df["crime_date"], errors="coerce")

In [17]:
df = df.dropna(subset=["crime_date"])

In [18]:
df["year"] = df["crime_date"].dt.year

In [19]:
df["month"] = df["crime_date"].dt.month

In [20]:
df["crime_hour"] = (
    pd.to_numeric(df["crime_hour"], errors="coerce")
    .fillna(0)
    .astype(int)
)

In [21]:
print(df[["crime_date", "year", "month", "crime_hour"]].head())
print(df.isnull().sum())

           crime_date  year  month  crime_hour
0 2020-01-01 02:00:00  2020      1          14
1 2020-01-01 14:00:00  2020      1          22
2 2020-01-02 12:00:00  2020      1           0
3 2020-01-03 08:00:00  2020      1          20
4 2020-01-03 09:00:00  2020      1           9
area           0
crime_type     0
year           0
crime_count    0
crime_date     0
crime_hour     0
day_night      0
month          0
dtype: int64

In [22]:
df["crime_type"] = (
    df["crime_type"]
    .str.strip()
    .str.upper()
)

In [23]:
print(df["crime_type"].value_counts())

crime_type
ASSAULT           1082
SEXUAL ASSAULT    1070
KIDNAPPING        1049
Name: count, dtype: int64

In [24]:
df = df.dropna(subset=["crime_type", "crime_count"])

In [26]:
df["crime_count"] = (
    pd.to_numeric(df["crime_count"], errors="coerce")
    .fillna(0)
    .astype(int)
)

df = df[df["crime_count"] > 0]

In [27]:
print(df[["crime_type", "crime_count"]].head())
print(df.isnull().sum())

       crime_type  crime_count
0      KIDNAPPING            1
1  SEXUAL ASSAULT            1
2  SEXUAL ASSAULT            1
3  SEXUAL ASSAULT            1
4         ASSAULT            1
area           0
crime_type     0
year           0
crime_count    0
crime_date     0
crime_hour     0
day_night      0
month          0
dtype: int64

In [28]:
df["crime_hour"] = df["crime_date"].dt.hour

In [29]:
print(df[["crime_date", "crime_hour"]].head())

           crime_date  crime_hour
0 2020-01-01 02:00:00           2
1 2020-01-01 14:00:00          14
2 2020-01-02 12:00:00          12
3 2020-01-03 08:00:00           8
4 2020-01-03 09:00:00           9

In [30]:
df["day_night"] = (
    df["crime_hour"]
    .apply(lambda h: "Day" if 6 <= h < 18 else "Night")
)

In [31]:
print(df["day_night"].value_counts())

day_night
Night    1613
Day      1588
Name: count, dtype: int64

In [32]:
mismatch = df[
    ((df["crime_hour"] >= 6) & (df["crime_hour"] < 18) & (df["day_night"] != "Day")) |
    (((df["crime_hour"] < 6) | (df["crime_hour"] >= 18)) & (df["day_night"] != "Night"))
]

print("Mismatched rows:", mismatch.shape[0])

Mismatched rows: 0

In [33]:
area_agg = (
    df.groupby("area", as_index=False)["crime_count"]
      .sum()
)

In [34]:
print(area_agg.head())

        area  crime_count
0       Agra           72
1  Ahmedabad          149
2  Bangalore          294
3     Bhopal           60
4    Chennai          182

In [35]:
low_q = area_agg["crime_count"].quantile(0.33)
high_q = area_agg["crime_count"].quantile(0.66)

print("Low threshold:", low_q)
print("High threshold:", high_q)

Low threshold: 57.480000000000004
High threshold: 105.00000000000001

In [36]:
def risk_label(x):
    if x <= low_q:
        return "Low"
    elif x <= high_q:
        return "Medium"
    else:
        return "High"

area_agg["risk_level"] = area_agg["crime_count"].apply(risk_label)

In [37]:
df = df.merge(
    area_agg[["area", "risk_level"]],
    on="area",
    how="left"
)

In [38]:
print(df["risk_level"].value_counts())
print(df.isnull().sum())

risk_level
High      2216
Medium     642
Low        343
Name: count, dtype: int64
area           0
crime_type     0
year           0
crime_count    0
crime_date     0
crime_hour     0
day_night      0
month          0
risk_level     0
dtype: int64

In [39]:
assert df["risk_level"].isnull().sum() == 0
print("STEP 7 COMPLETE — RISK LEVEL CREATED")

STEP 7 COMPLETE — RISK LEVEL CREATED

In [40]:
required_cols = [
    "area",
    "crime_type",
    "year",
    "crime_count",
    "crime_date",
    "crime_hour",
    "day_night",
    "risk_level"
]

In [41]:
missing = [c for c in required_cols if c not in df.columns]
print("Missing Columns:", missing)

Missing Columns: []

In [42]:
print(df[required_cols].isnull().sum())

area           0
crime_type     0
year           0
crime_count    0
crime_date     0
crime_hour     0
day_night      0
risk_level     0
dtype: int64

In [43]:
assert df[required_cols].isnull().sum().sum() == 0
print("FINAL VALIDATION PASSED — DATASET 1 READY")

FINAL VALIDATION PASSED — DATASET 1 READY

In [44]:
df.to_csv("final_crime_dataset_1.csv", index=False)

In [45]:
print(pd.read_csv("final_crime_dataset_1.csv").head())

        area      crime_type  year  crime_count           crime_date  \
0   Ludhiana      KIDNAPPING  2020            1  2020-01-01 02:00:00
1  Bangalore  SEXUAL ASSAULT  2020            1  2020-01-01 14:00:00
2    Lucknow  SEXUAL ASSAULT  2020            1  2020-01-02 12:00:00
3     Kanpur  SEXUAL ASSAULT  2020            1  2020-01-03 08:00:00
4  Ahmedabad         ASSAULT  2020            1  2020-01-03 09:00:00

   crime_hour day_night  month risk_level
0           2     Night      1     Medium
1          14       Day      1       High
2          12       Day      1       High
3           8       Day      1     Medium
4           9       Day      1       High

In [46]:
df["crime_count"].sum()

3201

In [47]:
df.groupby("area")["crime_count"].sum()

area
Agra              72
Ahmedabad        149
Bangalore        294
Bhopal            60
Chennai          182
Delhi            415
Faridabad         31
Ghaziabad         59
Hyderabad        208
Indore            59
Jaipur           119
Kalyan            29
Kanpur            92
Kolkata          212
Lucknow          118
Ludhiana          65
Meerut            37
Mumbai           366
Nagpur            81
Nashik            33
Patna             61
Pune             153
Rajkot            21
Srinagar          25
Surat             93
Thane             56
Varanasi          23
Vasai             31
Visakhapatnam     57
Name: crime_count, dtype: int32

In [48]:
df.groupby("crime_type")["crime_count"].sum()

crime_type
ASSAULT           1082
KIDNAPPING        1049
SEXUAL ASSAULT    1070
Name: crime_count, dtype: int32

In [49]:
df.groupby("day_night")["crime_count"].sum()

day_night
Day      1588
Night    1613
Name: crime_count, dtype: int32

In [50]:
df.groupby("year")["crime_count"].sum()

year
2020    814
2021    800
2022    421
2023    680
2024    486
Name: crime_count, dtype: int32

In [52]:
import pandas as pd

df2 = pd.read_csv(r"D:\Downloads\data\cleaned\ncrb_women_crimes_cleaned.csv")

print(df2.shape)
print(df2.columns.tolist())
print(df2.head())

(40897, 5)
['State', 'District', 'Year', 'Crime_Type', 'Crime_Count']
            State       District  Year Crime_Type  Crime_Count
0  ANDHRA PRADESH       ADILABAD  2001       RAPE           50
1  ANDHRA PRADESH      ANANTAPUR  2001       RAPE           23
2  ANDHRA PRADESH       CHITTOOR  2001       RAPE           27
3  ANDHRA PRADESH       CUDDAPAH  2001       RAPE           20
4  ANDHRA PRADESH  EAST GODAVARI  2001       RAPE           23

In [54]:
critical_cols = [
    "State", "District", "Year", "Crime_Type", "Crime_Count"
]

df2 = df2.dropna(subset=critical_cols)

In [55]:
print(df2.isnull().sum())

State          0
District       0
Year           0
Crime_Type     0
Crime_Count    0
dtype: int64

In [57]:
df2["Crime_Type"] = (
    df2["Crime_Type"]
    .str.strip()
    .str.upper()
)

In [59]:
df2["State"] = df2["State"].str.strip().str.upper()
df2["District"] = df2["District"].str.strip().str.upper()

In [61]:
df2["Crime_Count"] = (
    pd.to_numeric(df2["Crime_Count"], errors="coerce")
    .fillna(0)
    .astype(int)
)

df2 = df2[df2["Crime_Count"] > 0]

In [62]:
required_cols = [
    "State", "District", "Year", "Crime_Type", "Crime_Count"
]

missing = [c for c in required_cols if c not in df2.columns]
print("Missing Columns:", missing)

print(df2.isnull().sum())

Missing Columns: []
State          0
District       0
Year           0
Crime_Type     0
Crime_Count    0
dtype: int64

In [63]:
df2.to_csv("final_ncrb_women_crimes.csv", index=False)

In [64]:
import pandas as pd

df3 = pd.read_csv(r"D:\Downloads\data\cleaned\women_children_crimedata_cleaned.csv")

# standardize column names
df3.columns = df3.columns.str.strip().str.lower()

In [65]:
print(df3.shape)
print(df3.columns.tolist())
print(df3.head())

(12, 3)
['heads', 'year', 'count']
                                            heads  year  count
0                      NUMBER OF WOMEN TRAFFICKED  2016   5239
1                   NUMBER OF CHILDREN TRAFFICKED  2016   9034
2  NUMBER OF WOMEN VICTIMS OF TRAFFICKING RESCUED  2016   7238
3  NUMBER OF CHILD VICTIMS OF TRAFFICKING RESCUED  2016  14183
4                      NUMBER OF WOMEN TRAFFICKED  2017   2040

In [66]:
df4 = pd.read_csv(r"D:\Downloads\data\cleaned\women_children_crimedata_cleaned.csv")

df4.columns = df4.columns.str.strip().str.lower()

df4 = df4.rename(columns={
    "heads": "indicator",
    "count": "total_count"
})

In [67]:
df4["indicator"] = df4["indicator"].str.strip().str.upper()
df4["year"] = pd.to_numeric(df4["year"], errors="coerce").astype(int)
df4["total_count"] = pd.to_numeric(df4["total_count"], errors="coerce").astype(int)

df4 = df4.dropna(subset=["indicator", "year", "total_count"])

In [68]:
print(df4.shape)
print(df4.columns.tolist())
print(df4.head())

(12, 3)
['indicator', 'year', 'total_count']
                                        indicator  year  total_count
0                      NUMBER OF WOMEN TRAFFICKED  2016         5239
1                   NUMBER OF CHILDREN TRAFFICKED  2016         9034
2  NUMBER OF WOMEN VICTIMS OF TRAFFICKING RESCUED  2016         7238
3  NUMBER OF CHILD VICTIMS OF TRAFFICKING RESCUED  2016        14183
4                      NUMBER OF WOMEN TRAFFICKED  2017         2040

In [125]:
df4.to_csv("final_women_children_crimedata_cleaned.csv", index=False)

In [2]:
import pandas as pd

df5 = pd.read_csv(r"D:\Downloads\data\cleaned\women_outdoor_crimes_2024_cleaned.csv")

In [3]:
df5["crime_count"] = 1

In [4]:
df5["crime_type"] = (
    df5["OFFENSE"]
    .astype(str)
    .str.strip()
    .str.upper()
)

In [5]:
print(df5[["crime_type"]].head())

                   crime_type
0  ASSAULT W/DANGEROUS WEAPON
1  ASSAULT W/DANGEROUS WEAPON
2  ASSAULT W/DANGEROUS WEAPON
3  ASSAULT W/DANGEROUS WEAPON
4  ASSAULT W/DANGEROUS WEAPON

In [6]:
df5["crime_date"] = pd.to_datetime(df5["REPORT_DAT"], errors="coerce")

df5 = df5.dropna(subset=["crime_date"])

df5["crime_hour"] = df5["crime_date"].dt.hour
df5["year"] = df5["crime_date"].dt.year
df5["month"] = df5["crime_date"].dt.month

In [7]:
df5["day_night"] = df5["crime_hour"].apply(
    lambda h: "Day" if 6 <= h < 18 else "Night"
)

In [8]:
df5["area"] = df5["NEIGHBORHOOD_CLUSTER"]

In [9]:
area_agg = (
    df5.groupby("area", as_index=False)["crime_count"]
       .sum()
)

low_q = area_agg["crime_count"].quantile(0.33)
high_q = area_agg["crime_count"].quantile(0.66)

def risk_label(x):
    if x <= low_q:
        return "Low"
    elif x <= high_q:
        return "Medium"
    else:
        return "High"

area_agg["risk_level"] = area_agg["crime_count"].apply(risk_label)

df5 = df5.merge(
    area_agg[["area", "risk_level"]],
    on="area",
    how="left"
)

In [10]:
print(area_agg.head())
print(area_agg.shape)

         area  crime_count risk_level
0   Cluster 1           13     Medium
1  Cluster 10            2        Low
2  Cluster 11            1        Low
3  Cluster 12            3        Low
4  Cluster 14            6     Medium
(42, 3)

In [11]:
print("Low quantile (33%):", low_q)
print("High quantile (66%):", high_q)

Low quantile (33%): 5.530000000000001
High quantile (66%): 33.18000000000001

In [12]:
print(area_agg["risk_level"].value_counts())

risk_level
Medium    14
Low       14
High      14
Name: count, dtype: int64

In [13]:
df5 = df5.merge(
    area_agg[["area", "risk_level"]],
    on="area",
    how="left"
)

In [14]:
print(df5.columns.tolist())

['CCN', 'REPORT_DAT', 'START_DATE', 'END_DATE', 'SHIFT', 'OFFENSE', 'BLOCK', 'WARD', 'DISTRICT', 'NEIGHBORHOOD_CLUSTER', 'LATITUDE', 'LONGITUDE', 'hour', 'day', 'month', 'weekday', 'time_period', 'crime_count', 'crime_type', 'crime_date', 'crime_hour', 'year', 'day_night', 'area', 'risk_level_x', 'risk_level_y']

In [15]:
print(df5[["risk_level_x", "risk_level_y"]].head())

  risk_level_x risk_level_y
0       Medium       Medium
1         High         High
2       Medium       Medium
3         High         High
4         High         High

In [16]:
df5["risk_level"] = df5["risk_level_y"]

df5 = df5.drop(columns=["risk_level_x", "risk_level_y"])

In [17]:
print(df5.columns.tolist())

['CCN', 'REPORT_DAT', 'START_DATE', 'END_DATE', 'SHIFT', 'OFFENSE', 'BLOCK', 'WARD', 'DISTRICT', 'NEIGHBORHOOD_CLUSTER', 'LATITUDE', 'LONGITUDE', 'hour', 'day', 'month', 'weekday', 'time_period', 'crime_count', 'crime_type', 'crime_date', 'crime_hour', 'year', 'day_night', 'area', 'risk_level']

In [18]:

print(df5["risk_level"].value_counts())

risk_level
High      728
Medium    256
Low        43
Name: count, dtype: int64

In [93]:
print(df5["risk_level"].isnull().sum())

1

In [96]:
df5[df5["risk_level"].isnull()][["area", "NEIGHBORHOOD_CLUSTER"]]

   area NEIGHBORHOOD_CLUSTER
80  NaN                  NaN

In [97]:
df5["area"] = df5["area"].astype(str).str.strip()

In [98]:
df5 = df5.drop(columns=["risk_level"])

In [99]:
df5 = df5.merge(
    area_agg[["area", "risk_level"]],
    on="area",
    how="left"
)

In [100]:
print(df5["risk_level"].isnull().sum())

1

In [101]:
problem_row = df5[df5["risk_level"].isnull()]

print(problem_row)

         CCN                 REPORT_DAT                 START_DATE  \
80  24142281  2024-09-15 07:51:27+00:00  2024-09-15 04:20:00+00:00

                     END_DATE     SHIFT                     OFFENSE  \
80  2024-09-15 06:14:00+00:00  MIDNIGHT  ASSAULT W/DANGEROUS WEAPON

                                 BLOCK  WARD  DISTRICT NEIGHBORHOOD_CLUSTER  \
80  4700 - 4799 BLOCK OF 1ST STREET SW   NaN       7.0                  NaN

    ...  weekday  time_period  crime_count                  crime_type  \
80  ...   Sunday        Night            1  ASSAULT W/DANGEROUS WEAPON

                  crime_date crime_hour  year  day_night area risk_level
80 2024-09-15 07:51:27+00:00          7  2024        Day  nan        NaN

[1 rows x 25 columns]

In [102]:
df5["risk_level"] = df5["risk_level"].fillna("Medium")

In [104]:
print(df5["risk_level"].isnull().sum())

0

In [105]:
df5.to_csv("final_women_outdoor_crimes_2024.csv", index=False)

In [107]:
print(df5.head())
print(df5.columns.tolist())

        CCN                 REPORT_DAT                 START_DATE  \
0  24001558  2024-01-04 02:09:24+00:00  2024-01-03 23:03:00+00:00
1  24019819  2024-02-08 04:29:10+00:00  2024-02-08 01:25:00+00:00
2  24022148  2024-02-12 16:25:56+00:00  2024-02-12 15:30:00+00:00
3  24005258  2024-01-11 13:51:09+00:00  2024-01-11 12:10:00+00:00
4  24005185  2024-01-11 07:35:50+00:00  2024-01-11 04:56:00+00:00

                    END_DATE     SHIFT                     OFFENSE  \
0  2024-01-04 00:26:00+00:00   EVENING  ASSAULT W/DANGEROUS WEAPON
1  2024-02-09 03:30:00+00:00  MIDNIGHT  ASSAULT W/DANGEROUS WEAPON
2  2024-02-12 16:15:00+00:00       DAY  ASSAULT W/DANGEROUS WEAPON
3  2024-01-11 12:15:00+00:00       DAY  ASSAULT W/DANGEROUS WEAPON
4  2024-01-11 04:59:00+00:00  MIDNIGHT  ASSAULT W/DANGEROUS WEAPON

                                               BLOCK  WARD  DISTRICT  \
0                 1953 - 2099 BLOCK OF 19TH PLACE SE   8.0       7.0
1  3900 - 3999 BLOCK OF MARTIN LUTHER KING JR AVE...   8.0       7.0
2              1737 - 1776 BLOCK OF COLUMBIA ROAD NW   1.0       3.0
3              100 - 199 BLOCK OF ATLANTIC STREET SE   8.0       7.0
4             1000 - 1099 BLOCK OF WEBSTER STREET NW   4.0       4.0

  NEIGHBORHOOD_CLUSTER  ...    weekday  time_period  crime_count  \
0           Cluster 28  ...  Wednesday        Night            1
1           Cluster 39  ...   Thursday        Night            1
2            Cluster 1  ...     Monday    Afternoon            1
3           Cluster 39  ...   Thursday    Afternoon            1
4           Cluster 18  ...   Thursday        Night            1

                   crime_type                crime_date crime_hour  year  \
0  ASSAULT W/DANGEROUS WEAPON 2024-01-04 02:09:24+00:00          2  2024
1  ASSAULT W/DANGEROUS WEAPON 2024-02-08 04:29:10+00:00          4  2024
2  ASSAULT W/DANGEROUS WEAPON 2024-02-12 16:25:56+00:00         16  2024
3  ASSAULT W/DANGEROUS WEAPON 2024-01-11 13:51:09+00:00         13  2024
4  ASSAULT W/DANGEROUS WEAPON 2024-01-11 07:35:50+00:00          7  2024

   day_night        area risk_level
0      Night  Cluster 28     Medium
1      Night  Cluster 39       High
2        Day   Cluster 1     Medium
3        Day  Cluster 39       High
4        Day  Cluster 18       High

[5 rows x 25 columns]
['CCN', 'REPORT_DAT', 'START_DATE', 'END_DATE', 'SHIFT', 'OFFENSE', 'BLOCK', 'WARD', 'DISTRICT', 'NEIGHBORHOOD_CLUSTER', 'LATITUDE', 'LONGITUDE', 'hour', 'day', 'month', 'weekday', 'time_period', 'crime_count', 'crime_type', 'crime_date', 'crime_hour', 'year', 'day_night', 'area', 'risk_level']

In [109]:
import pandas as pd

df6 = pd.read_csv(r"D:\Downloads\data\cleaned\cleaned_outdoor_women_crimes_2017.csv")

In [110]:
print(df6.shape)
print(df6.columns.tolist())

(5003, 16)
['year', 'state_name', 'district_name', 'outdoor_women_crime_total', 'rape_women_above_18', 'rape_girls_below_18', 'attempt_to_commit_rape_above_18', 'attempt_to_commit_rape_girls_below_18', 'sexual_assault_of_children', 'assault_on_womenabove_18', 'assault_on_women_below_18', 'kidnapping_and_abduction', 'kidnapping_for_ransom', 'kidnapping_and_abduction_of_women_others', 'human_trafficking', 'procuration_of_minor_girls']

In [111]:
id_cols = ["year", "state_name", "district_name", "outdoor_women_crime_total"]

crime_cols = [c for c in df6.columns if c not in id_cols]

print("Number of crime-type columns:", len(crime_cols))
print(crime_cols[:10])  # preview

Number of crime-type columns: 12
['rape_women_above_18', 'rape_girls_below_18', 'attempt_to_commit_rape_above_18', 'attempt_to_commit_rape_girls_below_18', 'sexual_assault_of_children', 'assault_on_womenabove_18', 'assault_on_women_below_18', 'kidnapping_and_abduction', 'kidnapping_for_ransom', 'kidnapping_and_abduction_of_women_others']

In [112]:
df6_long = df6.melt(
    id_vars=["year", "state_name", "district_name"],
    value_vars=crime_cols,
    var_name="crime_type",
    value_name="crime_count"
)

In [113]:
print(df6_long.shape)
print(df6_long.head())

(60036, 5)
   year      state_name  district_name           crime_type  crime_count
0  2017  ANDHRA PRADESH  ANANTHAPURAMU  rape_women_above_18           20
1  2017  ANDHRA PRADESH       CHITTOOR  rape_women_above_18            6
2  2017  ANDHRA PRADESH         Y.S.R.  rape_women_above_18           23
3  2017  ANDHRA PRADESH  EAST GODAVARI  rape_women_above_18           19
4  2017  ANDHRA PRADESH  ANANTHAPURAMU  rape_women_above_18            0

In [114]:
df6_long = df6_long[df6_long["crime_count"] > 0]

In [115]:
print(df6_long.shape)
print(df6_long["crime_count"].describe())

(26251, 5)
count    26251.000000
mean        43.153975
std         81.549522
min          1.000000
25%          4.000000
50%         15.000000
75%         47.000000
max       2069.000000
Name: crime_count, dtype: float64

In [116]:
df6_long = df6_long.rename(columns={
    "state_name": "state",
    "district_name": "district"
})

In [117]:
df6_long["crime_type"] = (
    df6_long["crime_type"]
    .str.strip()
    .str.upper()
)

In [118]:
df6_long["year"] = df6_long["year"].astype(int)
df6_long["crime_count"] = df6_long["crime_count"].astype(int)

In [119]:
print(df6_long.isnull().sum())          # all zeros expected
print(df6_long.head())
print(df6_long.columns.tolist())

year           0
state          0
district       0
crime_type     0
crime_count    0
dtype: int64
   year           state       district           crime_type  crime_count
0  2017  ANDHRA PRADESH  ANANTHAPURAMU  RAPE_WOMEN_ABOVE_18           20
1  2017  ANDHRA PRADESH       CHITTOOR  RAPE_WOMEN_ABOVE_18            6
2  2017  ANDHRA PRADESH         Y.S.R.  RAPE_WOMEN_ABOVE_18           23
3  2017  ANDHRA PRADESH  EAST GODAVARI  RAPE_WOMEN_ABOVE_18           19
5  2017  ANDHRA PRADESH         GUNTUR  RAPE_WOMEN_ABOVE_18           32
['year', 'state', 'district', 'crime_type', 'crime_count']

In [123]:
df6_check = pd.read_csv("final_outdoor_women_crimes_2017_normalized.csv")
print(df6_check.head())
print(df6_check.shape)

   year           state       district           crime_type  crime_count
0  2017  ANDHRA PRADESH  ANANTHAPURAMU  RAPE_WOMEN_ABOVE_18           20
1  2017  ANDHRA PRADESH       CHITTOOR  RAPE_WOMEN_ABOVE_18            6
2  2017  ANDHRA PRADESH         Y.S.R.  RAPE_WOMEN_ABOVE_18           23
3  2017  ANDHRA PRADESH  EAST GODAVARI  RAPE_WOMEN_ABOVE_18           19
4  2017  ANDHRA PRADESH         GUNTUR  RAPE_WOMEN_ABOVE_18           32
(26251, 5)

In [121]:
import os
print(os.getcwd())

C:\Users\Ankitha\Big Data

In [122]:
df6_long.to_csv(
    "final_outdoor_women_crimes_2017_normalized.csv",
    index=False
)